# 結論

OSにとって重要な課題は、影響力と可視性のレベルが不均等なさまざまな実践の諸システムから生じる、オープン性に対する異なる解釈とその運用の間の衝突を生産的に管理することであると私は主張してきた。このような不公平は、それが目下の諸システムのメリットや目的適合性によるものではなく、社会的状況によるものである場合、認識論的不正義を生み出し、科学的成果の質を低下させる。一見したところこの課題は、純粋に実践的なもののように思えるかもしれない（OSの概念化というより実装の問題であるかのように）。また、科学的知識の質・内容にはほとんど影響を与えない純粋に倫理的な懸念のように見えるかもしれない。しかし、これらの印象はどちらも間違っている。代わりに私が示したのは、多様な研究環境においてOSを実装する際に遭遇する困難は、科学がどのように機能し、かつ機能すべきか、という哲学的な仮定に結びついているということである。

私の見立てでは、多くのOSの取り組み、特に制度化されたトップダウン型のアプローチは、オブジェクト指向の研究観に基礎づけられており、その中でオープン性は、データ・モデル・論文などのアイテム化された研究成果物を共有する自由、そしてもっとも洗練されたバージョンでは、再利用する自由として理解されている。OSの哲学に対するこのアプローチは適切でも望ましいものでもない。そこでは、成果のアクセス可能性を向上させることが科学的知識の質と研究実践の包摂性を向上させるのに役立つと仮定されている。また、研究コンポーネントの共有それ自体を科学の目的とすることで、OSの取り組みを諸々のオブジェクトの取引と管理に集中させている。それとは対照的に、OSの実践は、アクセス可能な状態が提供される具体的な仕方、特に固有の研究状況において誰が貢献者とみなされるのか、諸々のオブジェクトはどのように扱われ解釈されるべきか、どのような目的が追求されるべきかを決定するために用いられる戦略に焦点を当てることで、科学的な成果物の質をよりよく支援することができると私は提案した。この枠組みでは、データ・モデル・論文などの研究成果物を進行中の探究プロセスの一時的な道標としてとらえ、その機能は、研究コミュニティ内外のコミュニケーションや学びを適切に支援することである。これはプロセス指向の科学哲学であり、成果物がどのような条件のもとで生み出され、流通し、保管され、展開されていくかということに注意を向けさせ、また、科学研究を主にアクティブな知識を発展させることを狙いとしたものとして概念化するものである。オープン性は、単に諸資源を共有するという問題なのではなく、世界とのより適合的な相互作用の形態を発展させるのに役立つような仕方で、研究プロセスにおいて関連する利害関係者（専門の研究者、一般市民、非人間である生物、機械など）との間のつながりをつくり維持する機会として概念化される。誰が関連する利害関係者とみなされるべきかということは特定の研究の文脈においてのみ確立されうるもので、それは、研究条件に影響を及ぼす可能性のある認識論的不正義の形態を緩和することを目指しながら、同時に、目下の目的に関連しうる諸々の観点の多様さを考慮するという思慮深き区別を伴う。

思慮深いつながりを育むプラットフォームとしてOSを位置づけることで、OSの取り組みの焦点は研究者らの知り方・やり方・他者とのあり方に当てられることになる。そのスポットライトは、研究の成果物を特定し、科学的探究の受益者および／ないし科学的探究に対する貢献者となるものは誰かを適切に裁定するうえで研究者らが用いる境界の規準を含め、諸々の研究コンポーネントや成果物を批判的に精査することを促すような認識論的活動へと移る。実践の諸システム内で設定された優先順位を研究者がより自覚できるように奨励することは、研究が実施される科学的・社会的な環境に応答するような仕方で研究の透明性と質を向上させるためには欠くことができない。多様性と不正義の両方について考慮することは、OS実装の障害になるということでは決してなく、OS運動の理念を実現させるための重要なステップとなるのであって、同時に、OSが支配的な研究レパートリーに囚われ、不公平で保守的で差別的で欠陥のある研究アプローチを否定する機会をもたらす。

こうしたオープン性のビジョンをどのようにうまく実現しるうかということは依然として未解決の問題である。これは研究者たち、特に「ベストプラクティス」の規準や標準が明確に定義され、めったに疑問視されない高度に決定づけられた設定の場で働く研究者たちに対して、建設的に自身らの境界戦略に向き合い、それら戦略を目下の問いにあうように調整していくのに役立つ可能性のあるつながりを求める、という大きな要求を課す。これは単に、諸々の結果を伝えるのによりよい技術を見つけるという事案ではない。それは多くの場合、科学における公衆や参加者とはいったい誰なのかということに対する既存の認識に対峙することを意味し、翻って、どの研究成果物をいつどのように普及させるかを決定するのに役立つことになる。ときにOSの支持者は、研究文化の根本的な変化の一部としてそのような要求をとらえており、研究者自身によってそれは推進されるべきだと主張している。しかし私たちは、科学的な実践というものが、どのように制度化されたインセンティブと報酬の諸システムによって制約され足場が組まれているかをここまで見てきたわけで、それらを介して研究は支援・評価されているのであって、包摂的なOSの取り組みでは莫大なコストがかかるのはいうまでもなく——コミュニケーションの場とチャネルを整備し、かつ長年にわたってそれらを維持する必要がある——、個々のプロジェクトや研究グループだけが負担できるものではない。OSの実装は、個人に任されているわけでも、適切な技術を開発するという問題でもない。それは適切な形態のガバナンス・インフラ・資金・集合的エージェンシーを要求する、システムの変更である。ここで再び、ポパーの「開かれた社会」に関する考察が提起した問いに戻る。科学の組織化は、社会条件によってどのくらい規定されてしまうのか。そして科学機関は、同時にそうした諸システムがもつ浸透しやすい性質、科学的な知識生産がもつ非独善的で参加型の性質を損なうことなしに、ある特定の時点で研究実践の諸システムに正当に属するものの境界を区切る必要性にどのように対処できるのか。

OSガバナンスにとって鍵となる課題のひとつは*規模*である。特定のコミュニティや目的・領域を対象としたオープンサイエンスのプロジェクトは、既存のつながりにもとづいて新しい出会いを促すことができる。その一例としては、特定の生物や疾患の研究に関連した手法を再利用しやすくするために作成された取扱説明書、データベース、フィールドブックがあげられ、というのもこうした取り組みの多くには、（地理的には分散しているが）比較的一貫した認識論的コミュニティが存在しており、人々は互いに知り合いで、互いの仕事を評価する仕方も何がしか確立されている。このような取り組みを拡張させるには、潜在的に関連するさまざまな実践の諸システムを疎外することなく、思慮深いつながりを促すのに十分な共通の土台を見つけることを伴う（Chen et al. 2019）。将来的な参加者らは貢献者としての自律性を主張する必要があり、同時に、参加対象の取り組みから学んでいく——これは多くの場合、ローカルな目的に関連して諸々の標準を文脈化し、精査し、修正できる場や情報システムへ投資することを意味している（Kelty 2019）。

多くのOSの取り組みが、「データ管理計画」から、所与の研究デザインを基礎づける論拠と仮定を記録する事前登録制度（プレレジストレーション）の手順に至るまで、科学的労働を形式化し記述する新たな方法を提案することで規模の問題に応えてきた。これは、*官僚主義*という別の重要な課題をもたらす。このようなツールは、ある一連の成果物を文脈化し、それらの妥当性・重要性・将来的な可能性を評価するのに役立ち、結果責任を高めることができる。しかし（共有することとしてオープン性を解釈する場合、一般的には必要となるように）研究者たちにこうしたツールの採用を迫ると、研究の管理・経営的な側面を増大させるとともに、追加の事務作業を発生させ、調査に充てる時間が削られることになる。それが研究の目的や状況に釣り合う場合には十分正当化されるけれども、研究報告に関するガイドライン（reporting guidelines）が研究実践とずれている場合は非常に問題となる。さらに、事前登録制度などのツールが、科学者が当初約束したことを実行したかどうかを確認するために使われるようになると、OSは諸々の機関や資金提供者が研究実践を統制する別の手段となってしまう恐れがある。これは、誰がこうした新しいタイプの成果物を評価する専門知・時間・動機をもっているかは不明確なため、研究者の創造性を阻害しかねず、必ずしもよりよい品質チェックにつながるわけではない形の監視である。思慮深いつながりとしてのオープン性という見方は、研究を統制するために諸々のOSツールを用いることから離れ、代わりに、研究に利用し研究で調査する諸システムを統制する自分たちの戦略を研究者らが特定し、それを問い直すのを支援することに焦点を当てている。たとえばデータ管理計画や事前登録制度といったツールを用いて、研究がどのように進んだのか、なぜそうなったのかを追跡する場合、研究者らがあらかじめ決められた台本に従うことを期待していない。これは、インフラの開発と学際的な対話を学術的精神の中心に置き、競争を二次的な役割にすることで、研究の優先順位と評価システムの大幅な再編成を必要とする。

学術的な優先順位や制度の内部的な方向転換を超える最大の課題（議論されにくい難題）は、OSの取り組みが、科学が不可避的にその中に位置づけられる政治勢力および経済構造によってどの程度*道具化*されやすいかということである。OSが共有を目指しているのか、思慮深いつながりを目指しているのかを考えることに、果たしてどれほどの意味があるのだろうか。ほとんどの研究成果物が、どのような科学的調査でもその終盤は知識を取引したり収用したりすることになるようなオブジェクト指向の研究システム内に埋もれているとしたらどうだろうか。公的資金で賄われた研究による諸結果が、恩恵を受けるものの階層が定められた企業構造へ最終的に取り込まれてしまうとしたら、そのガバナンスについて議論することに意味はあるのだろうか。

科学研究の諸々のプロセスや成果物が、公的資金によるものだろうが民間資金によるものだろうが関係なく、グローバルな政治経済により過度に規定されていることの影響の大きさは、いくら強調してもしすぎることはない。それでも、私はこれを理由にOSや科学そのものを完全に諦めるべきだとは考えない。たとえば作物データ共有の事例を再考してみよう。たしかに、実践コミュニティによって慎重に構築されたデータガバナンスのシステムが、OSの取り組みから利益をえようとする農業技術企業によって妨害され、作物に関する知識が社会的・環境的に健全でない形態の農業に利用される可能性はある。また、作物データ共有の搾取的な性質が、コミュニティ主導のOSの取り組みを通じて国際的な注目を集めたことも、たとえば国連食糧農業機関（FAO）のようなよく知られた機関が新自由主義市場におけるデータの過剰な資本化に関する懸念を支持していることも事実である。その結果、国レベルの農業戦略や、生物多様性条約のような国際的な合意では、データライセンス、データのサイロ化、利益配分に関する協定をめぐる諸テーマが議題にあげられており、それによりOSを、参加者に対してより責任をもち応答性のあるものにしていくことの重要性が強調されている。

あるいは、オープンアクセスの著者負担モデルをめぐる現在進行形の議論について考えてみよう。これらのモデルでは、著者がオープンアクセス出版物の制作と流通にかかる諸費用を負担する責任を負う。研究者らが適切な資金を利用できる場合、このモデルは実装が容易である。出版社はそれらのサービスに対して報酬をえて、著者は論文を発表でき、諸結果はペイウォールなし（無料）でアクセス可能となる。しかし資金の調達は容易ではないことが多く、たとえ調達できたとしても、研究システムのほかの部分から諸資源を捻出することになる。このため著者負担モデルを推奨することは、既存の脆弱性や研究者間の格差をさらに悪化させ、研究環境全体に壊滅的な結果をもたらす可能性が高い。そうであるにもかかわらず、このような事態が過去10年間でまさに進行しているように見え、Plan S のような有名なOSの取り組みでは、利用可能な財源という点で学問分野や地域を超えて研究者間に存在する深刻な不公平さを考慮しないまま、商業出版社の利益率を維持する仕方で著者負担モデルを支持しているように思われる。しかし、この状況が放置されているわけではない。Plan Sの多くのアンバサダー（私自身も含めて）は、こうしたスキーム内での著者負担モデルに加担することに反対しており、このシステムが裕福な機関に拠点を置く研究者に累積的な優位性を与えてしまうことを文書としてまとめあげるために多くの労力が割かれている（Ross-Hellauer et al. 2022）。その結果、Plan Sは現在、オープンアクセス出版の代替的な形態を積極的に模索しており、諸々の学協会や機関は、研究システム内の出版構造および商業出版社の役割がもたらす科学的・社会的な課題にこれまで以上に注目するようになってきている。

最後に、コロナウイルス研究について考えてみたい。パンデミックの間、データへのアクセス・精確性・その利用に関する諸々の問題は、マスメディアやソーシャルネットワーク上で日々の論争の対象となり、GISAIDのようなデータインフラは予期せぬ社会政治的役割を果たすことになった。第3章で議論したように、これは科学コミュニティ内に摩擦を生み出したが、OSインフラが果たすべきコミットメントや目的はどのようなものか、それはなぜか、誰のためにか、といった洗練された議論も醸成している（Johnson et al. 2022）。いいかえれば、これらの摩擦はOSの政治性を浮き彫りにした。この状況は、一部の研究者にとっては驚きで、ただ発見する目的から純粋に技術的な共有プラットフォームをつくっていると考えていた科学者たちにとっては不快感を生じさせるものとなった。そうしたプラットフォームが社会における科学の役割に関する規範的なビジョンなしには存在できなかったということだからだ。しかし、そのような規範的ビジョンの重要性を認識することは研究にとって欠かせない一歩であり、最近のいくつかのOSの取り組みや政策でも発現し出している。Research Data Alliance（研究データ同盟）のような組織では、10年前はデータ共有のための技術的手段を提供することに重点が置かれていたが、現在はその使命を、科学にさまざまな人々が関われるように促すという方向へと拡大させており、データの収集・処理・解釈に持ち込むことが可能な専門知をそうした人々が有していることが認識されたことで、そうした結びつきは進められている。また、オブジェクトを共有することに重点を置くのではなく、そうした共有を責任あるものとする諸条件により焦点を当てた「インテリジェントなオープン性」への呼びかけが盛んになっている（Boulton et al., 2012; Bilder et al., 2020）。さらに、ユネスコが2021年に発表したオープンサイエンスに関する勧告では、（私が科学技術データ委員会の同僚や世界中の何百ものOS組織と共に参加した）広範な協議をもとに、必要な開始点として、成果物よりプロセスを、競争よりも共同作業を、スピードよりも包摂を優先する重要性が強調されている（UNESCO 2021）。

このような特性をOSの状況は、特に研究が制度化され評価され、ガバナンスの対象とされる仕方に大規模な転換が起きているこの時代に、この領域への概念的な介入が価値あるものとなるという希望を与えてくれる。OS運動の存在そのものは、研究者がコミュニケーションを図り共同作業をおこなうやり方、そして研究プロセスのさまざまな段階でさまざまなツールにアクセスして利用できる程度が、知識の発展にとって中心的な問題となるという認識にもとづいている。OSの言説が現在のブームを超えて続くかどうかは別として、新たにつくられた諸々のインフラおよび標準は、科学が将来どのように追求され、社会でどのような役割を果たすかということに対して長く残り続ける影響を及ぼすことになるだろう。長年にわたる共同・共有への呼びかけは、ビッグデータとAIの時代を特徴づけてきたスピードとデジタルによる自動化へと向かう推進力——政治的に分裂した世界を特徴づける研究およびデータ交換の政治経済——によって再構成されている。このような意味でOSは、研究がどのように遂行され、それがどのように制度化されるかということに対して長期的な影響を及ぼす政治的・経済的・文化的な契機を示すものである。オープンサイエンスの取り組みは、科学的な手法やコミュニケーションのモデルだけでなく、研究そのものの意味やその成果物の性質をも変えようとしている。これは、OS内でなされた概念的仮定と、研究実践におけるオープン性の具体化を科学的・社会的・倫理的に強固なものとする諸々の仕方について特定・評価する重要性を浮き彫りにしている。
