# はじめに

オープン性（openness）は長らく、透明で自由かつ包摂的な探究という認識論的意義に対するとらえ方が政治的・科学的な正当性の源となる自由民主主義にとって、指針となる原則とされてきた。政治家が、有権者に対する結果責任（アカウンタビリティ）がどのくらい果たされているかという受け止められ方を通じてその信頼性と影響力をえているように、科学者は、その調査が研究に有用なのか、適用できる範囲はどのくらいなのかという受け止められ方を通じて、信頼性と影響力をえている。オープン性は往々にして、結果に対する責任や公の精査を補完するために必要なものとみなされている。カール・ポパーからユルゲン・ハーバーマス、ヘレン・ロンジーノ、フィリップ・キッチャーに至る哲学者が主張するように、独裁者と選挙で選ばれたリーダー（あるいは科学者とペテン師）を区別するものは、その意思決定過程がどのくらい可視化され、理解でき、批判を受け入れることができるかどうかという点にある。

オープンサイエンス（OS）運動は、研究の諸々の成果物、コンポーネント（構成要素）、手法が、科学と社会の益のために幅広く普及し、精査され、再利用されることを保証することに重きを置いており、政治的・科学的な結果責任の歴史的な共進化における最新章にすぎない。この意味で、この動きは目新しいものでも驚くべきものでもなく、たとえば定説に対する批判的な問いかけ、信頼できる証拠の探求、合理的な推論の尊重、公の精査・討議の重視など、長い間、科学研究を定義づけるものとみなされてきた価値観との強い連続性を保っている。同時にOSは、研究のデジタル化、グローバル化、コモディティ化によってもたらされた広範な変容への対応として、過去30年間、勢いを増してきた。新たな技術と増え続ける従事者により、発見の量と速度が大幅に増加するにつれ、効果的なコミュニケーションをめぐる問題はより緊急性を増しており、科学研究機関は、現代世界の共同的な要件にその実践を適応させようと苦闘している。このような進展に対応しようとしていることに限っていえば、OSはまったく新しい。現状構築されている研究システムを変革することが明確に目指されており、つまり、諸々の科学プロセスの解釈・実行・評価のされ方に革命がもたらされる可能性がある。

この変革の要点は、科学的な探究の途上で生み出される成果物の多面性・多様性に改めて注目することにある。オープンサイエンスは、書籍や論文だけでなく、データ・モデル・ソフトウェア・技法・機器・サンプルなど、そして科学コミュニケーションや評価システムの中で間違いなく過小評価されてきた認識論的価値を含む成果物をより目立たせ、活用できるような、研究実践・評価・ガバナンスを再設計する機会として広く描かれている。つまり、研究論文やデータ、モデルに対する無料かつ即時のアクセスを保証するデジタルインフラ（「オープンアクセス」「オープンデータ」「オープンメソッド」）が活況を呈している。研究手段を記録し、いずれ再現できるようにするためのデジタルラボノートなど、標準化されたノートテーキングツールもある（「オープンノート」）。また、既存知識に対する独創的な貢献を求めるのではなく、つまり誰にとって特に意義がありうるかといった前提を必ずしも設けずに、研究成果の頑健性および妥当性を評価したうえで、高品質な結果すべてを公開することを促すようなレビュー制度が出てきた（「オープン査読」）。そして、国・分野・専門領域・文化の境界を超えて、（特に科学者でない人たちの知見を研究に取り入れる市民参画という形を通じて）知見や資材を交換することを促す共同的な場がある（「シティズンサイエンス」「コミュニティサイエンス」）。世界中の公的機関や民間機関はOSの取り組みを支援する戦略を策定しており、その範囲には国レベルのロードマップから、国際的な取り決め、オンライン出版のプラットフォーム、研究の質に関して更新された評価制度、学術成果に関して改訂された評価基準が含まれる。政治家らもこうした動きを意欲的に受け入れており、将来的なイノベーションのために[^1]、基礎研究を「科学資本」に変えうる効果的な仕組みとしてOSは位置づけられている。すなわち、オープン性がもつ政治的役割と科学的役割の間には深い結びつきのあることが再び示されている。企業の役員室から大学の経営陣、そして政治的な場においても、OSの意義とその実装に関する議論は最上位の議題にまでなってきている。

[^1]: 第二次世界大戦後にヴァネヴァー・ブッシュが推進した、20世紀の科学政策における積年の課題。

本稿では、現代の研究におけるOSの認識論的役割について、哲学的な知見にもとづく解釈を提示する。OSの方針および実践が研究手法や成果物にどのような影響を与えるのか、科学的探究の性質と構造にとってOSはどのような意味をもつのか、そして世界に関する知識の追求との関連において、オープン性という考え自体がどのように理解されうるのか、また理解されるべきなのか。本稿は現在のOSの実践を純粋に記述的にとらえたものではなく、以下に簡単に後述するように、こうした実践に長く関わってきたことが私の見解に強い影響を与えている。つまり、むしろ本稿はOSの歴史・動機・可能性について規範的な解釈を提示するものであり、OSの現在の実践を特徴づけるおおまかな傾向に焦点を当てるものである。私の目的は、OS運動の中でしばしばなされる透明性と共有へのコミットメント——私の見立てでは、この点が、信頼に足る責任ある研究を促進するというこの運動の試みを阻害することになる——について、建設的な形で批判的に読み解くことである。私は、この懸念に対処するための第一歩は異なる哲学的立場を採ることだと主張したい。オープン性を、主に資源を共有することとして概念化するのではなく、むしろ主に、研究に携わる人同士の有意義なコミュニケーションを促進することとして概念化したい。このような広範な議論をおこなうためには、不可避的に、OS運動がもつ一般的な特徴を示す必要があるが、その複雑さや多面性をきちんと評価するものではない。そこで、あらかじめ断っておきたい。本稿は、OSという取り組みの広大かつ多様な景観を包括的な仕方でとらえることを意図しているわけではなく、またOSの中には、私が好む、つながりとしてのオープン性という理解に実際のところ従っている場合も多々ある。とはいえ私の分析は、特に大規模なOCの取り組みや政策にしばしば見受けられる言説やコミットメントについて扱うもので、私の見解では、それは批判的な議論に値する。それゆえ本稿では、OSの歴史と現在の機能をめぐる実証的な研究にもとづくものの、明示的に規範的な観点に立脚したうえで、そうした資料の解釈をおこなう。

このアプローチは、スタンドポイント理論および強い客観性（Harding 1995）という伝統における認識論に不可欠なものとして倫理を理解することを反映しており、またそうした理解に触発されたものでもある。それによれば、ある主題に対する誰かの観点とは、常にその誰かの背景や目的によって色づけられた「どこかからの視点」にすぎない。本稿における私の全体的な関心事は、この地球上の生命を持続させることを目的とした研究にとってオープン性がどのような意味をもちうるのか、もつべきなのかということについて、哲学的な枠組みを提示することにより、OSの将来的な発展を支えることにある。私は特に、公共善を追求するためにOSを利用することに関心があり、そのような「善」が関わる人々や文脈によってどのような形となるのかということについて、既存の理解を深めることにも興味がある[^2]。全体を通じてこのような哲学的立場を維持するため、私は一貫して、研究実践の分析を基礎づけるものとして、認識論的な考察と倫理的な考察とを絡めていくことになる。これから説明するように、OSに関する一部の実践がはらむ差別的・排他的な意味合いをめぐる倫理的な問題と、そうした実践を通じて生み出される研究の信頼性や頑健性をめぐる認識論的な問題とを切り離すことはできない。サンプリング、表象、モデル化、コミュニケーション、解釈といった手順の方法論的な健全さは、技術的な特性と社会的な文脈の両方に依存せざるをえない[^3]。

[^2]: この立場は、Longino (1990)、Kitcher (2001)、Wylie (2003)、Rouse (1987, 2015)、Potochnik (2017)、Cartwright et al. (2022)、Chang (2022) などで示されている同様の見解にもとづく。
[^3]: Beaulieu and Leonelli (2021) および Thompson (2022)

歴史的に見て、ここでは2つの相補的な観察結果を開始点としたい。第一は、本稿執筆時点の研究において、オープン性を追求することが抜本的に重要になっていることである。ワールドワイドウェブや関連する通信技術の台頭を受けて1980年代に高まった諸々の希望は、デジタルツールがアイデアの自由な流通や批判的な精査を抑制させ、複雑なものとし、あるいは誤った方向へ導くように広く用いられるようになった現在、失望へと変わりつつある。リベラルな考え方の礎石としてオープン性が輝かしい歴史を刻んできたにもかかわらず、2020年代は、そのことがどのような意味をもちうるにせよ、「[オープン性という] それ自体のためのオープン性」をナイーブに求めるような時代ではない。インターネットは企業が独占する場となり、フェイクニュースが真摯な議論の試みを圧倒する脅威となるにつれ、自由な情報という考えの危険性と誤用が誰の目にも明らかになってきた。このことは、科学研究に関連してオープン性が概念化され、実行に移されていく仕方に重大な影響を及ぼす。

第二の観察結果は、その実現に向けた善意と多大な労力をよそに、OSの取り組みは、多くの困難を抱えており、まさにそうした取り組みの対象であるはずの研究コミュニティからも抵抗を受ける場合がある。この観察結果はOSの実装を主眼とした国際的な学術研究の増加によって裏づけられており、それには、私自身が過去10数年にわたり自然科学および社会科学分野の同僚らと共同で実施した大規模な質的調査も含まれる。これは、国や分野を超えて、研究者らがOSをどのようにとらえ、自分たちの仕事にそれがどのような意味合いをもつと認識しているのかを探るものであった。結果、研究者が適切な支援とトレーニングを受けている状況では、OSは科学的な議論の質および包摂性を高めることができることを確認した。しかし大半の研究者は国際的に知名度が低く十分な資金もない、および／ないし、OSにかけた労力に報いる気配もない分野や機関で働いている。このような研究者らにとって、自らの研究を支えるためにOSのインフラを使うことは難しい。というのもそれは、開発するものたちのもつ関心事や前提・優先事項・スキル・技術資源がそうしたインフラを設計する際に反映されているためで、そうしたものたちの多くは資金力のある機関に所属し、このような活動について支援を受けられる英語を話す科学者らである[^4]。私はこのような活動を補完する形で、諸科学にまたがるオープン性や共同活動というアイデアの歴史を記録する研究をおこなうとともに、OSを実現させる条件を見定めるために、さまざまな研究組織や政策機関による大規模な取り組みにも個人的に関与してきた[^5]。このような経験を通じて、OSと関連することは何か、知識の生産と利用においてオープン性および透明性がどのような役割を果たすのかということについて、意見の相違が相当程度あることを私は目の当たりにしてきた[^6]。私の分析は「科学をオープンなものにする」という政治的なスローガンと関連させて、滑らかに語っていくのではなく、そうした摩擦の根源や意味合いについて検討するところから出発したい。

[^4]: Leonelli (2016), Levin et al. (2016), Bezuidenhout et al. (2017), Chan et al. (2019), Leonelli (2022a), Ross-Hellauer et al. (2022)。研究者間でもたれているもうひとつの顕著な心配の種は、営利機関（デジタル封建主義へと向かっている全体的な傾向については次を参照。Jensen 2020）や政治的な理由から科学の諸結果を歪曲することに関心をもつ組織（たとえば、気候変動をめぐる議論については次を参照。Lewandowsky and Bishop 2016, Nerlich et al. 2018）によるOSの搾取についてである。
[^5]: 私が科学政策の世界に足を踏み入れたのは、2007年からビッグデータの認識論についておこなってきた研究がきっかけである。そこでは、科学の変革に向けてデータを結集させ再利用する斬新な手法の重要性を浮き彫りにした。このような研究の報告を求められたことから、オープンデータ、オープンアクセス、OSインフラをめぐる数多くの議論に参加するようになり、グローバルヤングアカデミー、欧州委員会、Plan S、国際科学会議などで研究者代表や専門委員を務めるようになった。諸々の報告書類はプロジェクトOpen Science Studies のウェブサイト（[https://opensciencestudies.eu](https://opensciencestudies.eu)）上で公開されている。学術界からこうした政策論争に関与した経験について振り返られた文献としては Burgelman (2021), Miedema (2021), Owen et al. (2021) を参照のこと。
[^6]: 主に生物学や生物医学における科学的実践の研究にもとづいてはいるが、私の分析では、社会科学や人文学も包含することを意図している。私は、社会科学者や哲学・歴史学・文学研究の方々との交流を通じて、また、社会科学や人文学のポートフォリオを監督する研究組織での顧問としての役割を通じて、それらの観点について学んだ。このような射程の幅広さに鑑み、本文では科学という用語を人文学・社会学・自然科学を含むドイツ語Wissenschaftの意味合いで用いる。

重要な問題は、研究の経路・成果物・参加者を増やすことに重点をおくOSが、世界中のさまざまな研究コミュニティにより利用されている既存の多様な認識論的実践、ひいては研究がなされるさまざまな社会・政治的環境とどのように関連しているのかが明確になっていないことである。OSの環境で活動するには効果的なコミュニケーションが必要であり、そのためには共通の手順・基準・原則・指標に関してある程度のコンセンサスが求められることは広く認識されている。いいかえると、どのように科学をオープンにしていくかという判断は、不可避的に、何を「よい」科学とみなすか、またそうでないかを判断することでもある[^7]。OSのインフラが信頼できる知識源として機能する限り、それはまた、疑わしい研究実践を特定し、取り締まるツールとしても機能するということだ。このような要件に応えるため、より制度化されたOSの取り組みにおいては大概の場合、科学的方法について、多元的で状況に依存するものよりも、均質で普遍的に適用可能なものとして理解されていることを優先してしまいがちである。科学が共通の規範に準拠しうる、そして準拠すべき首尾一貫した知識と手順の体系から構成されていると仮定すると、OSのガイドラインを設定することははるかに容易なものとなるだろう。だがこの仮定は、諸々の領域や場所や文脈で研究アプローチがすさまじいほどに数多く存在することだとか、強固で包括的かつ信頼できるような形でこの世界のことを理解するにはそうした多元性が重要となることを見過ごしている[^8]。

[^7]: OSに関する議論と科学全体に関する議論を厳密に区別し続けることが不可能なのもこのためである。本稿ではOSに焦点を当てるが、往々にして、そして不可避的に、21世紀における研究のあり方をめぐるより広範な議論、そしてそれが未来の科学的な実践および政策にとって何を意味するのかということを含むような形で話は拡大していく。
[^8]: 科学の多元主義に関する学術的知見には膨大な蓄積があり、本稿ではそれらについて包括的にレビューすることなどできない。第4章では、科学哲学の文献を主として、重要な側面に焦点を絞りたい。

これまでのところ、世界中の研究者らがそれぞれ固有の目的や作業条件に合うようにつくり、実行しているベストプラクティスの標準や基準とオープン性がどのように関係しているかということについて、体系的な理解はなされていない。以下では、そのような理解が欠落していると、一部のOSの取り組みで求められている高度な標準化および精度の高い検証という実践が、知るという行為において盲目的に特定の仕方を優先させてしまい、その結果、洗練された方法論を崩壊させ、確立された研究の伝統を意図しないまま否定し、すでに大規模に存在する、研究の領域や実施場所を隔てる認識論的・社会的な隔たりを悪化させてしまう可能性があると主張する。科学および科学に関する諸研究において多くの論者が糾弾しているように、OS政策の中には——そこには善意や前進的な傾向が見受けられるにもかかわらず——研究における保守主義、差別、コモディティ化、不平等を強化する反動的な力として作用し、その結果、最終的にはOSが達成しようとしたものを悲惨な形で覆し探究の機会を閉ざしてしまう、そうした重大なリスクがある。私は、ローカルな知とその社会的な文脈に対する深い理解に立脚したOSの取り組みを強調することで、OSをそのような運命から救うことは可能であり、その方向への重要な一歩は、どのような科学的実践（つまりどのような*科学哲学*）がOS運動により設定された目的をもっともよく支えるものとなるかを明確化することだといいたい。本稿が寄与したいのはこの点であって、まずは研究コンポーネントの共有にオープン性を基礎づけるような解釈について、その起源や動機、そしてその意味合いの分析をおこなうことから取り掛かり、次に、多くの草の根的なOSプロジェクトでは、特定の仕方で知るという行為を関心事や選好や手法が常に支えているわけだが、そのことがすでに例証しているように、研究プロセスの網状的かつ分散的な発展を軸とする代替的な見方を擁護する。

この議論は4つの章（第2～5章）で構成される。第2章では、グローバルな研究状況を苦しませているシステム上の問題、特に研究コミュニケーションや共同研究、出版・公表に対する既存の制約に焦点を当てたうえで、*現代のOS運動の主な特徴*を概観するとともに、研究成果とみなされるものを拡大させ、そうした成果を可能な限り広く共有するためのインセンティブを提供することにより、そのような問題に対処しようとするOSの取り組みについて述べる。私は、多数のそうした取り組みの基礎にあるのは、研究プロセスのさまざまな段階で諸々の資源と知見を*共有する自由*としてのオープン性というビジョンであり、結果をより透明化するインセンティブが組み入れられることにより、研究の再現性およびアクセス可能性は高まり、探求のあり方がより包摂的な参加型で、信頼できるものとなっていくことが期待されると主張したい。原理的にこのOSというビジョンは、ますます不透明で排他的な、かつコモディティ化されたものになっている科学システムに対する有効な反応であって、揺るぎないもののように思われる。しかし私が懸念しているのは、このビジョンが実際の研究においてどのように機能しているのかということである。

第3章では、分析の焦点を理論から*日常の科学的作業におけるOSの実践*に移すことによって、この問いに立ち向かう。OSの具体化として、次の4つの例を簡単に検証する。(1) コロナウイルスのパンデミックを引き起こしたSARS-CoV-2ウイルスに関する生物学的なデータを共有する取り組みについて。これは緊急事態下での発見を促進するうえでOSの有効性を示したものとして広く称賛されている。(2) データやモデル、ソフトウェアの品質基準の評価に関して生じている現在の課題について、また、そのような評価が、諸々の技術がデータの妥当性を高める、または保証さえする可能性があるという暗黙の仮定にどのくらい依存しているかということについて。(3) 作物およびその環境に関して各地域でえられたデータをつなぎあわせるための国際規模のインフラ開発について。これは食糧安全保障およびプラネタリーヘルス（地球の健康）の研究にとって極めて重要であるにもかかわらず、データの生産者と利用者の間に平等でない状況がすでに存在してしまっている。(4) 信頼できる研究手法を構成する規準として再現性という観念が特定の解釈で用いられていることについて。これらの例は、一方で、現代科学における目的・価値観・対象・背景知識・物質的環境は非常に多様なものであるから、ベストプラクティスとして期待されるものもさまざまであることを示しており、他方で、このような多様性が、科学的な諸資源の迅速かつ円滑な共有を求める動きによって、いかに押し潰される可能性があるかということ、つまりそれによって科学の進展が損なわれかねないし、同時に第2章で論じられるシステム上の諸問題に対処できていないことをも示している。

オープン性に関するひとつの解釈を探り、研究実践においてそれが不十分なことがわかったため、次なる段階は、科学の多様性とともに研究者がどのように研究を遂行し、コミュニケーションをとり議論するかということに関する研究からえられた経験的知見についてよりうまく説明できそうなオープン性に関する別の解釈を探ることとなる。この狙いのために第4章では、科学の多元性に関する哲学文献にもとづき、*研究実践システムの中心的な特徴である4点を特定*する。私の見立てでは、それらはOSの取り組みで認められ、支えられる必要がある。具体的には、(1) ローカルな条件に対する特殊性、(2) 研究範囲内での堅牢性、(3) 新参者に対する透過性、(4) 境界戦略である。この分析から、研究条件が所在場所によりどのように変わるのか、特定の研究遂行方法に誰が含まれており誰は除外されているのか、そして探究の構造や生み出される知識にどのような意味合いをもつのかということを考慮することなしに、科学的な手順および成果物の質を向上させることなど、あるいは評価することさえできないと結論づける。最後に私は、*認識論的多様性*と*認識論的不正義*の相互関係について論じ、両者が善なる科学の発展において重要な役割を果たし、それらをOSの取り組みの中心に据える必要がある、と主張する。

第3章と第4章でOS実践について分析をおこなうことにより、第5章では、ここまで論じてきた批判を拡大させ、信頼でき責任ある研究実践の探究をよりうまく支えるような代替ビジョンを描くことが可能となる。そのためには、共有としてのオープン性という考えの認識論的基盤をさらに掘り下げていかなければならない。この見方は、*科学の認識論*を、諸資源の統制の問題として、*オブジェクト指向の枠組み*でとらえることと絡み合っていると私は考えており、つまりそこでは、どのような形の専門知が研究プロセスにもたらされるかという問いは、具体的な成果物の生産だったり、そのような成果物についてどのような取引をすれば価値を生み出せるかということに関する標準的な手順や取り決めを策定したりすることに比べて、二次的な扱いとなる。そのような枠組みにおける科学は、事実・方法・知見の蓄積で構成されるものとみなされ、技術的に洗練されたインフラに支えられつつそれらが自由に流通していけば、研究の進展が図られるとともに、喫緊の課題に対処するためにそれら諸資源が社会のさまざまな部分で展開されていく機会も担保されることになる。私の見立てではこのような研究観は誤解を招くものであって非現実的であり、オープン性に対するこうした理解では、長期的に見てOS運動に結びつくような認識論的な便益がもたらされる可能性は低い。これは技術的に媒介された諸資源の共有が科学の発展に関連していないからではなく、むしろ信頼でき責任あるOSを遂行するには、共有することが必要な出発点でもなければ十分条件でもないためである。代替案として私は思慮深いつながりとしてのオープン性という構想を提案した。これはある状況に位置づけられ具現化されており、目的に向かって進められるような、研究者間のコミュニケーションや共同作業がもつ性質を認めるプロセス指向の科学認識論に基礎づけられている。このようなオープン性の理解は、さまざまな仕方でなされる活動や世界に対するさまざまな理解のなされ方を互いに関連づけるような人間の営みとして科学のダイナミクスを強調するものであり、したがって、成果物の選択や組織化、解釈は非常にさまざまな形となることが促される。この解釈のもとでは、オープンアクセスは、出版物へのアクセスを無料にすることだけで達成されるものではなく、むしろ著者が掲載料を支払えるかどうかに関係なく、その品質に対する公正な評価にもとづき出版が促進されることにより達成されるのである。オープンメソッドとは、研究手順の詳細すべてを記録して共有することではなく、むしろ、どの研究コンポーネントおよび技法が成果物にもっとも関連しているかということを反映させたものであって、つまりそれらにアクセスでき、それらは再現可能なものであるべきだ。シティズンサイエンスとは、研究プロセスに参画させることなくデータ収集の労働集約的な部分を参加者に委ねるということではなく、むしろ関連する知見をもたらしてくれる、専門家ではない一般市民と関係を構築していくことである。オープンデータとは、デジタルプラットフォーム上に研究データをただ蓄積することを意味するのではなく、むしろ、すべてのデータが利用できるとは限らず、また利用可能にすべきでもないということを認識したうえで、どのデータを共有するのか、またそのようなデータを創造的に探索できるようにするにはデータインフラがどのような支援をおこないうるかといったことについて、選択がなされなければならないし、かつそれは正当化されなければならない。

このようなOSの枠組みでは、信頼できる知識を生み出すための指針として、認識論的な多様性と正義を掲げている。オープンサイエンスの取り組みでは、科学的貢献とみなされるのはどのようなものか、それはどのような目的のために、誰によってなされるものなのか、といったことを明示的かつ定期的に問う必要がある。これは、効果的な共有というものは、研究および研究コンポーネントの価値と目的に関して、十分に正当化され、文脈化された弁別・判断のうえに成り立っていると認識することを意味する。判断をしないだとか、研究を条件づける特異性や、「すべてを利用可能にする」ような関連の試みを無視するということでははない。つまり、科学的発見は社会的な、状況化された企てとして位置づけられるのであって、それゆえOSと、既存の優れた実践に対する理解、そして開かれた社会とはどのようなものでありうるのかという具体的な構想との結びつきが浮き彫りになるのである。