# OSの哲学について再考する

共有としてのオープン性という構想には欠陥があると論じたうえで、次の課題は、透明性ではなく包摂の観点に基礎づけられたオープン性という代替的な構想について概説することとなる。これが本章の課題だ。この目的のためにまず、共有と透明性を重視するOSの哲学的ルーツを探る必要がある。以下では、科学の諸成果を使用・動員し価値あるものにするための取り組みとして科学的探究を概念化するのは問題であると主張したい。いいかえれば、オープン性を共有することとして理解するのはオブジェクト指向の科学観を前提としているということであり、そこではコモディティ化され安定しており取引可能な諸資源を利用できるかどうかで、新しい知識をえるのにそれらのオブジェクト（モノ）を研究者がどのように用いるかが決定づけられる。対照的に私はプロセス指向の視点を前提としたオープン性の哲学を提唱するが、そこでは研究はまずもって、広く多様な諸個人や諸集団における親密な形態の関係性および信頼に基礎づけられる集合的なエージェンシー（行為者性／力）を育む取り組みとして理解される——あるエージェンシーは往々にしてさまざまな技術的手段、研究成果に関して共有された解釈、人間以外のエージェント（行為者）との共同作業を通じて成り立っている[^23]。社会認識論および科学実践の経験的研究に基礎づけられたこのような研究観ではオープン性を研究者間で*思慮深い*つながりを探求することとして理解する。これらのつながりは、常にオブジェクト（モノ）や技術の交換により媒介されるが、そのような交換へとつながりが還元されてしまうことは決してないだろう。というのも、そうでないと、絶えず変化する世界と人間が有意味に相互作用しあうことを科学が支える力を失ってしまうためである。このようなOSの哲学は、研究で遂行されることをよりよく記述するものとなるし、知識がどのように生成されるかということに関してよりよい規範的立場にもなる、と私は主張する。

[^23]: 有機体や機械を含む人間以外の存在が研究実践の形成にしばしば寄与する独自のエージェンシーをもつことは認識しているが、ここでは科学・技術の目的や成果を生み出し評価する作業を担う人間同士の相互作用に焦点を当てる。

## 共有としてのオープン性とオブジェクト指向の科学観

ここまで、OSの多くの取り組みの根底にある共有という考えを、科学的調査に関連すると考えられる諸資源へ制約なしにアクセスできるようになる機会として理解することができるかもしれないことを見てきた。そのような諸資源には、手法・技法・スキルなど、研究をおこなうある仕方も含まれるだろうが、モデル・コード・データ・サンプル・出版物などのオブジェクト（モノ）が関連すると大抵の場合は理解されている。これらのオブジェクトが貴重なのは、知識が引き出される主な資材やツールをそれらが構成していると仮定されているためである。特にデータは根拠の有力な発生源になるものとして重宝されており、より多くのデータが生成され、研究者が利用できるようになればなるほど、それらのデータが解釈され、十分に裏づけされた知識要求に変換される可能性が高まるという期待——ビッグデータの革命的な力に執着する現状に顕著に表れている——がもたれている（Leonelli 2016）。

私がオブジェクト指向の科学観と呼ぶ、知識生産に関するこうした理解は、経験的知見の重要な源として帰納的推論を好む西洋の傾向と結びついている。アリストテレスが観察を好んだことから、フランシス・ベーコンが「ナマの（根源的な）事実」を集めて分析するように勧めたことに至るまで、西洋科学の営みの歴史、そして関連する諸制度は、主に研究成果の収用と操作に基礎づけられており、多かれ少なかれ発見とは、事実・テキスト・測定値・観察・資材の収集から新たな知識要求の生成へと直線的に進歩するものと解釈されている。もちろんこれは一般的な傾向に過ぎず、多くの例外があり、それは多くの研究分野において理論が重要であることだとか、さまざまな形で演繹的推論がなされていることにより裏づけられる。しかし帰納的推論——利用可能なオブジェクト（通常は強力な研究機関によって体系的に収集された諸々の「情報源」と解釈されるモノ）の体系的な考察から知見をえることおおまかにはとらえられる——は経験的知識という考え自体の基盤になるものとして長きにわたり支持されてきたことは認めてもよいと私は思う。そして、科学の進歩の仕方に関するこのようなオブジェクト指向の理解が、知識をそこから引き出せるようにと、さらにより多くの諸資源を取りつかれたように集積することを盛り立てており、それにより、成長し続けることおよび将来的な利益を見込んで投機することを前提とした人類の発展の資本主義モデルとして現在の私たちが理解しているものを生んでいる（de Sousa Santos and Meneses 2020）。クリストフ・ボヌイユはこの探究様式を、自然を理解するための「資源主義的」アプローチとして指摘したが（Bonneuil 2019）、そこでは生物多様性という観念そのものが、遺伝的な諸資源の収集・研究——つまり遺伝的な資材は人間のもつ（作物に関するデータ連携のような）目的にあうように分離・動員・変換させうる有機体である——として解釈されている[^24]。同様の仮定がその他多数の種類の資材・手法・データの収集を支えている。たとえばプラネタリーヘルスの進化を記録した重要なドキュメントとして衛星画像があげられ、それらを継続的に集積・分析することは自然科学および社会科学の双方に対して情報を与えるし、かつ双方に変化をもたらしうる。あるいは、人間および非人間からなる諸々の生物の感染症の蔓延を追跡・予測するためのモデリング手法の集合体もあげられ、それらを比較することで、病原体が移動したり発達したりするような脅威に対して包括的な理解が可能となるかもしれない。

[^24]: この見解を支持する広範な文献の中には、トウモロコシ栽培に関するもの（Curry 2022）、大規模生産のために酵素代謝を利用・収用する特許の利用に関するもの（Landecker 近刊）がある。

このような科学的探究観のもとでは、既存の学問にアクセスすることがどのような調査でも可能性の条件となり、共有活動がOS実装において明らかに重要な点となる。オブジェクト指向の科学観について体系的な批判をおこなうことは本稿の範疇ではないし、世界を理解する、世界に介入する新たな仕方を導出することの重要性や、その多大な成功を否定するつもりもない。私が浮き彫りにしたいのはその主な特徴のうちの2点についてなのだが、オープン性、科学的実践、研究ガバナンスに対する理解に大きな影響を及ぼすことがわかるだろう。ひとつ目は一般的に*人間の認知能力が信頼できない*点で、特に人間による世界理解を形づくるうえで歴史（研究者個人の経歴とその社会的・制度的背景の両方）の役割が信頼できないという点だ[^25]。よく知られているようにベーコンは、推論が文化や社会的地位、言語に影響される仕方を含め、自身の状況や希望にあうように世界に関する自身の経験を歪め形づくり、結果としてえられる知識の価値を低下させるという、人間がもつ性向の症状として、「精神のイドラ」に対する警鐘を鳴らした。主観性という概念そのものが研究の主体と客体は分けられるものと想定され、その研究では中立的な「どこからでもないところからの眺め」を支持し、利害や価値観を剥ぎ取ることを前提とする。過去3世紀にわたり、人間のもつ偏見を科学から排除したいという願いは、発見を自動化する試みという形態をとるようにますますなっており、近年では人工知能（AI）ツールに依拠することを通じてヒューマンエラーを最小化すること——機械的客観性と呼ばれていたもの（Lorraine Daston and Peter Galison 1992）の可能性がつくりだされている——が目指されるようになっている。オンラインで共有される研究コンポーネントのうちでもっとも評価される特性のひとつが機械可読性であることは何も偶然ではない。そこで期待されていることは、AIシステムがより容易にデータを収集・処理できるようになればなるほど、そうしたシステムは多様な入力を認識・評価できるようによりよく訓練されていき、その結果、より洗練された分析が可能になる、というものだ。したがって、10,000種の植物種から抽出された画像データで訓練された植物認識システムは、1,000種の植物種データで訓練されたシステムよりも精確で信頼性が高いと期待され、全国規模の人口統計データで訓練されたアルゴリズムは、1都市のデータで訓練されたものよりもよい結果をもたらすと期待されている。

[^25]: ここではエナクティヴ主義者、埋め込まれ身体化され拡張された認知モデルを想定している。

より一般的にいうと、オブジェクト指向の科学観は、人がおこなう判断を偏見や認知的欠陥から救うことのできる研究手法には力があり、帰納的推論が客観的で文脈に依存しないものと立証する仕方が示されているという信念と往々にして結びついている。ビッグデータが有望視されているのは、いったん適切に整形・処理・標準化されれば研究結果は世界を精確に表象したものと受け取ってもよいといえ、それらのデータが生まれ利用されている状況とは関係なく結果の妥当性や証拠的価値を評価しうる、と期待されているからである[^26]。しかし第3章で検討した諸々の例はこの期待に疑問を投げかける。それらの例は、データの質および意味を査定するために用いられる基準が、データの生産に関わる人々の間に不平等な、ときに公正でない関係が認められる領域だったり社会的文脈だったりにより形づくられていること——多様な研究の状況を評価するうえでそうした基準が用いられている場合には、考慮しなければならない事実である——を示していた。ある植物認識システムが信頼できるかどうか、またどのような目的で使用されるかは、利用可能な画像データの量に依存するのと同じくらい、何を価値ある特徴とみなすかということにも依存するかもしれない。また、対象となる標本およびデータ処理ツールの代表性とえられた調査結果に対する説明責任を担保するために適切な措置が取られている場合、小規模な調査地域から適切にえられた人口統計データの方が、大規模な調査地域からえられたはるかに大規模な（しかし不均一な）データセットより好ましいこともあるかもしれない。それゆえ、研究コンポーネントを解釈するには、認識論的多様性および認識論的正義を考慮する必要がある。このようなコンポーネントを利用できるということは、適切な再利用の保証にはならない。それどころか、研究の対象が元々の文脈から離れれば離れるほど、その生産と処理を基礎づける境界戦略が、当該の研究対象が展開される新たな状況（目的・設定・参加者）に対応できているかどうか、またどのように対応できているかを評価することが一層難しくなる。このようにデータの標準化は、訓練された人間がおこなう評価を超える、完全に自動化されたデータ分析を必ずしも実現させるようなものではない。機械可読のデータになることで複数のAIシステム内での広範な普及や取り込みが進むにつれて、標準化されたフォーマットは、個別のケースごとに、データが新たな目的に見合う根拠の基盤になるものとして適切であるかどうかを評価するために研究者が熟練した判断をおこなう必要性を高める可能性がある。

[^26]: この見解に対する批判の詳細については、Leonelli (2016, 2020) を参照のこと。

現状のオープン性に対する理解に強く影響を与えているオブジェクト指向の科学観がもつ第二の特徴は、*所有*という考えが中心に置かれていることである。近代初期の科学機関が世界中から植民地のオブジェクト（モノ）を収用することで発展を遂げたように——科学的調査に資することが期待され、それらは西洋の博物館や学協会によって収集・保存されていった[^27]——現代のOSインフラも知識生成に関連するとみなされたオブジェクトを収集・管理し、流通させている。所有とは必ずしも、それらのオブジェクトを長期的にもつことを、あるいは独占的にもつことさえをも意味しない。ここではむしろ、手元にあるオブジェクトの用途をある程度統制し、それに応じてその特性を操作する力を示すこと受け止め、研究を実践するうえで不可欠な前提条件ととらえられる（文字どおり「自分のもの」にするという意味合いである）。研究成果や、研究中に生み出されたものではないが、たとえばソーシャルメディアのデータのような研究活動にとって役立つとみなされるオブジェクトの所有と管理をめぐる議論はOSを概念化・実装するどのような取り組みにおいても中心的な課題であり続けている。そうした議論は、場合によっては所有権の放棄を求める形をとる。たとえば公的資金の助成を受けた研究者は、共同作業および透明性という名のもと、見返りや正当な評価を期待せずに自身らのモデル・手法・データをオンライン上のインフラに提供するよう求められるかもしれない。一方、農家や医療患者といった知識創造に直接関与していない集団が、「Sharing is Caring（分けあうことは思いやること）」（あるいは、皮肉めいてはいるものの「科学への権利」）ということわざに集約されるように、社会全体の利益のために手法・資材・データを提供するよう求められるかもしれない。また、特定の交換条件について合意を交わすことで所有権を主張するというやり方にについて議論がなされることもある。それには（たとえばGISAIDの場合のように）ライセンス契約のような法的保護や、アクセスを管理するための技術手段が含まれる。いずれにせよ知的財産をめぐる議論は、所有権が行使され、何の資源がさらなる調査で利用可能になるかが決定される場であるため、多くのOS運動の領域において「オープン性」の概念化と実装という両面の震源地を構成している。

[^27]: たとえば英国王立協会はベーコン的な経験主義を具体化する明示的な取り組みである（Walsh 2018）。

共有することとしてオープン性を理解することが、所有権の主張をOSの中心に据えることになるというのは逆説的に思えるかもしれないが、それはたしかに新しい主張とはいえず、OS実践の歴史によって裏づけられるものである。クリストファー・ケルティは、1970年代から1980年代にかけてのオープンソフトウェアの出現について解説した代表的な書籍の中で、ソフトウェア開発のプロプライエタリな形態から脱却しようとする最初の推進力がどのようにしてすぐさまオープン性を「購入の自由」として理解することへと発展させていったかを浮き彫りにし（Kelty 2007, 149–51）、オープンなシステムにとって知的財産が重要な条件となると同時に「盲点」ともなることを明らかとした（ibid., 178）。（OS運動の台頭を支えた）自由交換という考えと（将来の繁栄と成果物に対する支配権獲得のための仕組みとして情報共有を重視する）新自由主義的な自由市場の支持との類似性を明確に示したのはケルティだけではない。2015年時点の欧州委員会によるOSの定義でも、OSがイノベーションと経済成長を実現するものとして明確に提示されていた。たしかに、マニュエル・カステルが「情報資本主義」と呼び、ナイジェル・スリフトが「知識資本主義」と名づけたもの——いいかえれば、コモディティ化された情報の成長の見通しおよび技術への不平等なアクセスをめぐって絶え間なくなされる推測に基礎づけられた知識システムのこと——を、OSの景観がどのように支援・強化しているかということについてつい考えてみたくなる（Wyatt et al. 2000）。（いまや経済成長を加速させる「新しい石油」として広く宣伝されている）データを流通させることが、公共・民間の両部門におけるOSの取り組みの基盤となる目的であり続けているのは何も偶然ではない。フィリップ・ミロウスキが主張しているように、オープンアクセス出版からオープンメソッドに至るまで、OSの実装に参加することで、出版社や製薬業界などの大企業の利益は増す可能性があり、えてしてそうである（Mirowski 2018）。

しかし、OSは科学研究のコモディティ化および閉鎖性や秘密性への傾向を破壊するものではなかったのだろうか。そして、諸々の研究コンポーネントに対する支配的な所有体制を攻撃することを明示的に掲げていたOSの取り組みは、オープン性の哲学について読み解いていくうえでどこに位置づけられるのだろうか。第2章で論じたように、研究対象となるモノの収用を目的とした仕組みや制度を破壊することがOS 運動に参加する多くの研究者や非営利組織にとって重要な動機であり続けている。こうした組織においてOSの実践とインフラは、所有権の主張を回避することを明確な狙いとするものと解釈されている[^28]。そうした取り組みにおける共有のとらえられ方は、制限なきアクセスというよりも制限なき再利用のことと解釈されている。その重点は、国境管理・制度的境界・知的所有権体制などのさまざまな制約を含め、人々が諸々の研究コンポーネント上で作業し、研究コンポーネントを利用する能力に対する既存の制約を破壊することに置かれている。このことについてOSの取り組みは、特にどのくらい既存の権力構造に挑戦し、制度との持続的な対話を続け、未来のための代替ビジョンを開発するためにさまざまな抗議形態を用いるかという点において、社会運動や活動家のロビー集団からインスピレーションをえている——その結果、最終的には彼ら自身が重要な政治的アクターとなっている（Della Porta and Diani 1999, Leonelli 2019b）。この見方によると、研究コンポーネントを収用しようとするどのような試みも問題視される可能性があり、実際、過去30年にわたるそれらの取り組みの多くは、所有権の主張に関わることを完全に拒否していることが特徴となっている。つまり研究の進歩とは、発見のプロセスに役立つ可能性のあるものを何でも（再）利用できるという包括許諾を支持し、既存の所有権構造を回避して、誰が何をどのような目的で所有しているかといったことに絡む慣習を打ち破ることでえられるという考えである。ここで再度、作物データの連携を支援する科学界の試みが有用な例となる。というのも、そうしたデータを共有するすぐれた取り組みの多くは、研究成果や（種子や遺伝資源などの）関連資料に対する国・企業の所有体制に直接関与するのではなく、むしろそうした問題には目もくれず、諸々の参加者を包摂し諸資源を共有するもっともよい方法はどのようなものかという点を重視している（Leonelli 2022a）。COVID-19のゲノムデータ交換プラットフォームにおいてもできるだけ多くの人がデータにアクセスしてすぐに使用できるようにすることに重点が置かれ、そうした共有の試みにどのような形態の収用やコモディティ化が結びついてしまう可能性があるか、そしてこれが共有インフラに対してデータ提供者がもつ信頼性と公平性の認識にどのような影響を及ぼすか、ということについてはほとんど考慮されていない。この態度は、生物学的なデータ共有に関するより広範な歴史に反映されている。よく知られているように、1990年代におこなわれたゲノムプロジェクトの諸結果をめぐる所有権の争いに端を発し、いわゆるバミューダ原則で定められたように、国際規模で配列データの自由かつ即時公開に向けた動きが生じたわけだが、その基本的な目的はデータの私有化を避けることであった（Maxson Jones et al. 2018）。データへの自由なアクセスとその再利用が優先されたことになるが、これは生物医学や農業関連の特許取得や企業戦略をそうした共有によりどのように促進させていくかという論点をなおざりにしている。これらの懸念は、オープンデータをめぐる科学的言説からもOS擁護者の視野からも外されていった。その結果、科学の認識論的経済が確立され、これは国際的かつ学際的なデータ交換の可能性に基礎づけられるが、そのような交換がおこなわれる規制、法的・経済的体制や、研究成果がコモディティとして川下に流されたあとの影響についてはほとんど気にもされないままである。

[^28]: この勢力はしばしばFAIR原則への訴えを動機づけている。FAIR原則とは、データを発見しやすく（Findable）、アクセスしやすく（Accessible）、相互運用しやすく（Interoperable）、再利用しやすく（Reuseable）することを狙いとしたものだ。複数の政策・研究機関で支持されているが、FAIR原則の実装には依然として困難が伴い、特にそれは、データの所有者は誰か、必要なインフラに誰が資金を提提供するのか、実際の再利用時の責任の所在や実行可能性を誰が評価するのかといった問いを投げかける必要があるためである。

一見すると、制限なき再利用としての共有という考えは、制限なきアクセスとしての共有という考えよりも、OSにとってはるかによい基盤となる。OSの取り組みに関わる多くの研究者にとって、その試みは、研究およびその成果の資本化を明示的に回避し、代わりにそれらを共通財として位置づけ、必要な人なら誰でも利用できるようにすることだ。単にアクセス機会を提供するだけでは諸資源の生産的な展開を保証するには不十分であるという事実は、この界隈では十分に認識されており、そのことは、具体的なアクセス形態がどのようにその後の利用時に反映されるか、あるいはどのように利用を決定づけるかということを考慮することなくただアクセスに焦点を当てるというレトリックに関していえば、大きな改善である。とはいえ、共有することを制限なきアクセスとみなす人々と、再利用することを強調する人々の間には、科学の認識論において顕著な類似点がある。両陣営とも、発見や斬新な洞察を促すためにさまざまな仕方でパッケージ化・流通され、組み立てられる必要があるモジュール型コンポーネントの集積体として科学的知識を描く傾向がある。共有を再利用することとして解釈することは、所有権および収用の体制と、信頼できる知識を追求することとの関連性を否定するように見えるが、コモディティ化されたオブジェクト（モノ）という成果物を共有することに焦点を当てることは、OSが科学のコンポーネントに対する統制を保持するか放棄するかという選択のうえに成り立つという考え——それ自体、研究を（精査され承認された）積み木のような構成要素の集合体からなるものとしてとらえるモジュール的な見方である——と同様に、依然として問題視されていない。再利用は諸々のオブジェクトへアクセスすることやそれらを操作することを前提としているため、オブジェクト指向の科学観の基盤となる認識論的前提を再現するものである。また、人間の認知能力に対する同様の不信感と、研究コンポーネントが組み立てられ解釈される時点でバイアスそれ自体が立ち現れる恐れもあることから、そうした組み立ての瞬間をより透明化させることが求められており、それにより検証が可能となり、分析がより信頼できるものになると期待されることになる。注目すべき点として、批判の焦点はほとんどの場合、公的資金でおこなわれた研究に置かれており、これはフェルナンデス・ピントが「非対称的扱い」と呼ぶもので、公的資金でおこなわれるものはより高い基準を満たすべきだという考えと結びついている（Fernandez Pinto 2020, 8）。この仮定は、企業秘密のもとで実施される科学活動がさまざまな問題を抱えていることを指摘した文献がこれまで多数蓄積されてきたこと（Oreskes and Conway 2010）、私企業が大量消費向けの財を開発し流通させるうえで重要な役割を演じているにも関わらず、そうした活動がプラネタリーヘルスに及ぼす長期的かつ体系的な影響に対して責任を取っていないこと（Landecker, forthcoming）に鑑みると、深く疑問が残る。より一般的には、科学をよりよいものしようと所有権・資本化の問題を回避する試みがなされているにもかかわらず、OS運動の一部には、公的資金にもとづく研究における研究コンポーネントを透明化させ、それらの自由な再利用を追求することと、オープンな諸資源が下流では商業化していることやトランスレーショナルリサーチ（橋渡し研究）に対する関心が欠如していることとの間には根本的な緊張関係がある。つまり知的財産はこうしたオープン性の解釈において中心的な役割を果たし続けているが、そのことは、関係する科学者らにとっては重要な関心事として知的財産がとらえられていないことによって、より際立つものとなっている。OSの活動家がこの点にこだわるかどうかは別として、データ共有の取り組みの多くを支えているのは、政府や資金提供者による財政支援の保証および「インパクト」の証拠という文字どおりの意味でも、共有されている諸々の研究成果が最終的には商業化され、既存の法・規制、経済体制を統制する諸資源および権力をもつ人々にとって利益の源になるだろう、という期待にある。

私の分析は厳しい結論に達した。オープン性が、収用ないし破壊、アクセスないし再利用に向けた取り組みとして概念化されるかどうかにかかわらず、これらの一見対立する陣営を支えているのは、科学研究の出発点としてオブジェクト化された諸資源を「共有する」という共通のビジョンである。このビジョンは、研究の構成要素と成果物のオブジェクト化が、世界はどのようなものであるかという存在論的肯定というより、特定の目的のための実践の諸システムを定義および画定するために研究者によりなされる一時的な仮定とどの程度いえるかという点を過小評価するものだ。別の論稿でジョン・デュプレと私はこうしたプロセスとその潜在的な危険性を、研究成果を現実の信頼に足る鏡として用いようとするあまり、その道具的・状況的価値が忘れられがちな、*諸手段の具象化*の一形態として説明した（Dupré and Leonelli 2022）。生物学者がコロナウイルス株について収集した遺伝子配列は、潜在的に有害な変異体を特定するのに役立つという、特有の認識論的役割を果たすことが期待されている。そのようなデータが、より一般的なウイルス生物学を代表していると確実に解釈できるかどうかは、今後の研究目的や条件に依存するだろうし、データが抽出されたウイルスサンプルが複雑で絶えず進化し多様化する微生物環境をたしかに代表しているかどうかが、適切な技能を有す研究者により評価されないといけないだろう。オブジェクト指向の科学観では、研究コンポーネントの代表性および研究の長期的な信頼性をめぐる諸々の懸念点は脇に置かれがちで、科学者が新しい目的のためにそうしたコンポーネントを再利用することを決定するたびに、彼らはおこなわなければならない判断の重要性を過小評価していることになる。諸々の研究コンポーネントは、特定の状況とは無関係にそれらの質や使いやすさを検証できる諸々のアイテムとして概念化され、つまり新しい発見に向けて迅速に展開することが容易になる。これは、認識論的に価値あるオブジェクトの抽出・統制・集積として科学的な認識枠組みを形づくることと共謀している、コモディティとしての研究コンポーネントという見方である。私はこの見方が長期的にはOSの実践を支える力を制限してしまうと考えている。人間による熟考をすぐれた研究の外側にあるものとして描写しようとするその試みは、認識論的正義と多様性をめぐる諸懸念を信頼できる知識の追求とは無関係なものとして迂回させてしまう可能性がある。

## 思慮深いつながりとしてのオープン性とプロセス思考の科学観

それでは、研究成果のコモディティ化とオブジェクト指向の認識論にそれほど結びつけない仕方でオープン性を概念化するために何が必要となるかを考えてみたい。私たちは異なる出発点、つまりプロセス指向の研究観を必要とする。その中における科学は、オブジェクトを所有し統制することに主眼を置くのではなく、（1）世界を理解し相互作用する人間の能力を支援し、（2）所与の発見に責任をもつ人々以外の諸集団によりコミュニケーションが図られ採用・検証されうる、むしろそうした仕方でうまく行動できることを重視するものとなる[^29]。

[^29]: オブジェクト指向の認識論の場合と同じように、プロセス指向の認識論という考えはここで議論できないくらいに深いルーツを有している（Dupré and Leonelli 2022）。私のアプローチは研究を現在進行形のプロセスとして概念化するという実践における科学哲学にもとづいている（Soler et al. 2014）。

プロセス指向の研究観は、チャンが「アクティブ」と呼ぶ知識に関する構想と整合している。それは、目的のある仕方である活動・介入を遂行・調整する力のことである——そうした調整された行為の狙いが調査の開始時点では十分に定義されていないとしても、あるいは調査の開始時に変更される可能性があると思えたとしても、である。ここでの目的にとってもっとも重要なのは、このような能力としての知識観が “情報の蓄積・検索に還元ないし従属されるべきではない”（Chang 2022）ということだ。もちろん、アクティブな知識には、データ・出版物・モデルなどの諸々のオブジェクトを用いて情報を保管・符号化することも含まれる。集合的な営みとしての科学の進歩は、現実のうちの所与の部分を表象し、および／ないし、世界へ具体的に介入できるように諸々のオブジェクトを収集および／ないし開発・操作・解釈することなしにはありえないだろう。そのようなオブジェクトは、アクティブな知識がそれらの形態を介して抽象化・カプセル化され、取引されるもので、つまりコミュニケーションや、科学的な調査の対人的・社会的性質に対して基礎となる物質的なアンカーとして機能する。このような意味で、どのような研究実践でもアクティブな知識をそれらにより交換・評価・修正できることになるテキスト・図・モデル・観察結果・測定結果・その他の人工物に必然的に依存しているし、OSの擁護者がオブジェクトの交換・共有をすぐれた科学的実践に関連するものとして強調しているのは正しい。しかし、諸々の研究オブジェクトの生産・取引を科学の第一の目的と解釈すべきではない。これらのオブジェクトを共有する究極の目的は、単に情報を伝達することではなく、推論（科学的な説明や理論をもたらす）ないし介入（世界と相互作用するための手法やツールを生み出す）といった形態のいずれにせよ、むしろ人間というエージェンシー（行為者性／力）を促進することにある。したがって、研究者がその証拠的価値を評価する手段がない場合、データを共有しても無意味となる可能性があるし、あるいは、個々のデータポイントの特徴ではなく、データから浮かび上がる全体のパターン（データモデル）に調査の焦点が当てられている場合、データの共有は不要となる可能性がある。同様に、研究プロトコルにアクセスできるようにしても、関連する機器や訓練やインフラを用いることができない場合にはそれほど役に立たない。

諸々の研究オブジェクトを共有することは、本来人間の手による人工物で、調査に関連するとみなされるものそのものが時空間に位置づけられており、将来的に問われる可能性のあるものを、その来歴や処理のなされ方にかかわらず解釈可能な中立的な産物へと変換するためのひとつの仕方のこととしてみなされるべきではない。諸々のオブジェクトが調査者に情報をもたらすかどうか、どのように情報をもたらすかということは、調査の条件・目的や、それらオブジェクトの歴史と、それらの作成開発に参加した人々の動機・背景に関して適切に理解できるかどうかということに依存する（Morgan 2010）。化石や生物学的標本などの物質的なサンプルでさえ、それらが何を表象し、どのような洞察を促す可能性があるかということに対する特定の期待に従って位置づけられ保管・処理されている（Currie 2018, Ankeny and Leonelli 2020, Wylie 2021）。これらのオブジェクトは、デジタル化されたデータや数学モデルとまさしく同じように、研究実践の特定の瞬間の物質的なスナップショットに過ぎない。それらは、時間を超越してそれら自体にある、時間を超越したそれら自体についての科学的成果として数えられることが意図されているのではなく、アクティブな知識を増加させることを狙いとした認識論的活動のために位置づけられた足場として機能することが意図されている。したがって、研究におけるそれらの妥当性・関連性・重要性は、科学・世界・人間の願望における絶え間ない変化に合わせて定期的に再評価・調整される必要がある。科学的知識に対するこのアプローチの直接的な意味合いは、人間の諸目的に対するそのポジショナリティ（立ち位置）を認めるということである。研究の究極の目的を、（現実という枠組みを組み立て、現実について説明するために位置づけられた諸々の仕方を含め）人間による理解を促し、世界への介入に情報をもたらしうるスキルの育成ととらえるのならば、研究オブジェクトの生成・利用を規範的な前提から自由なものとして扱うことはできない。むしろ、貢献者のポジショナリティと科学的追求にもちこまれる観点の多様さについては、研究プロセスと切り離せないものとして認識され、明示的に議論される必要がある 。したがってプロセス指向の見方では、研究実践の諸システムを基礎づける境界戦略の認識論的・社会的な意味合いを体系的に検証することを含め、認識論的な不正義および多様性に関する懸念を科学の中心に据える。そうした懸念を科学の周辺に追いやるのではない。

このような科学的認識論の枠組みは、研究におけるオープン性の概念化に影響を与える。これまでOSのスポットライトは共有としてのオープン性という解釈に当てられていたが、以下ではプロセス指向の見方がそれを遠ざけ、代わりに*研究者間の思慮深いつながりを確立すること*としてオープン性を解釈する方向へ導くことを提案する。これらのつながりは通常、技術や特定の研究環境（その中には人間や非人間の参加者を含む）に精通していることにより媒介・構成される。この考えを解き明かすために、つながり（connection）という観念について論じることが始めたい。*Cambridge English Dictionary* ではこの語について主に次の3つの定義が示されている。最初の定義では関係性に焦点が当られ、つながりとは “誰かないし何かほかのものと関連している状態” として記されている。ふたつ目のものでは、関係性がその中で確立される環境がどのようにそうした関係性の足場となりうるかということにより重点が置かれている。つまりつながりとは “何かほかのものに結合するか結合される行為、あるいはそれを可能にする部分ないしプロセス” のことだという。3つ目の定義はつながりの確立に関与する諸実体の認知状態を浮き彫りにしており、“誰かや何かを理解し、好きになり、それらに興味が湧いている感情” というものである。つながりをOSの核となる活動および目的と理解するうえで、これら3つの次元はすべて不可欠なものとなる。つながりとは何よりもまず、別の実体と関わるプロセス、あるいは、自身の前提や確立された実践（研究の場合は自身の境界戦略）を打ち破る可能性のある仕方で存在するプロセスのことである。この関わり合いのプロセスは、技術的手段や具体的なオブジェクトを介してつながることから、さらに、社会的な絆の構築だとか、新たな関係が世界に対する自身の現状理解を揺さぶるかもしれないが、そうしたことへの対峙だとかを感情的に求めていくことまであげられるように、さまざまな仕方で足場が組まれている。実際、つながりのプロセスは、関与する「他者」が自分自身と異なれば異なるほど、より困難なものとなる。オープン性という考えは、自身の境界を乗り越えていく学びの考えと本質的に結びついている。これは、研究グループや個々の学習者と同じくらい、研究実践の諸システムにも間違いなく当てはまる。新しいつながりを確立するとは、多くの場合、自身の学びを拡大させること、所与のシステムの外部にある、ないしそれとは関係ないとみなされるものに関する既存の仮定を問い直すこと、さらに、新しい関係を組み込んだ新たな境界を確立させる必要があるかどうかを検討することを意味する。知識を探求する足場となる多くのオブジェクト・生物・資材などを含め、所与の探究状況を取り巻く環境は、つながりを形成・維持することが可能となるような景観全体を示すものである。そして人間の認知・感情の状態（つながることへの関心や、それが自らのアイデンティティ、社会的関係、世界に関する仮定について、自身の感覚からするとどのような意味をもつのかを探ることへの関心を含む）は、不可避的にその景観の一部となっている[^31]。

[^31]: この点についてここでは論じられないが、私は感情を人間の認知の基盤とする見方を支持している（Colombetti 2014を参照のこと）。

これらの抽象的なアイデアを具体化するために、つながりの構築に中心的な役割を与えるOSの実践例をふたつ取り上げてみたい。ひとつ目は、短期的で限定的な接続を支援することに重点を置いたものである。これはCrowdfightのようなプラットフォームの出現に代表されるもので、特定の具体的なタスクを手伝ってくれる意欲と能力のある人を研究者が特定できるようにするとともに、そのタスクを中心とした共同作業を促し、成果の分配プロセスを管理することを狙いとしている。その目的は、時間に限りのあるボランティア活動を通じて連帯と多様性への目配りを実現させることにあって、それにより研究者は自身の勤務条件や、現状の居場所を超えてつながりや責任の範囲を拡大したという意欲に応じて、自分たちのスケジュールにそうした活動を組み入れることが可能となるかもしれない。Crowdfightは2020年にCOVID-19の研究に取り組んでいる研究者らを結びつけるために創設され、初年度に4万5千人以上のボランティアを集めることに成功し、その結果、いくつかのイノベーションを生み、科学論文まで発表された。新たなつながりを築くことに成功したのは、国際規模の差し迫った脅威に立ち向かうため、科学者たちが通常の活動を中断するよう世界的に呼びかけられたことと明らかに関係がある。限定的な相互作用に絞ることで、極めて非常に忙しい研究者でもボランティア活動を管理可能なものとしている。本稿の目的にとってもっとも重要なのは、人々が自分で問題を解決できるような基準やツールを提供することよりも、目の前の問題を理解し対処するうえで人間同士の相互作用に断固として重点を置いていることである。したがって支援を求める研究者は、単にウェブサイトやツールを紹介され、「使い方」動画を観るように求められるのではない。彼らは、関連するツールの使用経験がある人々や、ほかの人がそうしたツールを使えるように案内したり、それらツールが彼らの問いに役立つかどうか、またどのように役立つかどうか判断したりするのを助けたいと考える人々と接触することになる。デジタル化されたコミュニケーションと共同作業のプラットフォームが飛躍的に進歩したことで、この種のつながりが可能になり、生産的になったことは明らかだ。同時に、そうしたプラットフォームのユーザ基盤を拡大するには、新たな問題や、既存の諸ツールが新たな目的や多様な研究文化に役立つ（あるいは役立たない）可能性のある仕方を見極める人的なつながりが欠かせないことも認識されている。

マイクロ共同作業のシステムとして、Crowdfightは、共通の目的達成に向けた善意のコミュニケーションという長年にわたり続くオープンソースの理念のうえに構築されており、それはたとえばGitHubなどで具現化されており、プログラミングスキルが限られている、あるいはそうしたスキルをもたないが研究をおこなっているものを含め、さまざまな人々がアクセスできるようになっている。このような専門知を超えたつながりの仕組みが、ほかの領域においても、気候変動がもたらす包括的な緊急事態との関連でも機能するかどうかはまだわからない。いずれにせよ、マイクロ共同作業の諸システムは競争主導の科学的状況に対抗するものであり、研究を包摂的でサービス指向のものとしてとらえなおし、研究の場所や条件を異にするものとも結びつける、管理可能な仕方を提案するものである。これらのシステムでは、日常的な問題に取り組むことがより多様な研究経験を可視化するための重要な一歩になり、それによって研究システムをより多様な参加者層に向けて再調整できるようになると認識されている。この知見は、草の根的なOSの取り組みの成功例に関する既往研究と一致している。その例として、Open and Collaborative Science in Development Network（OCSDNet）による調査があげられる。OCSDNetは、グローバルサウスの国々を含む、諸国にまたがるOS事業の共同プロジェクトで、次のような知見がえられたという。“諸々の共通の関心事を共有する他者とともに知識を共創し、つながり、参加する力は、単にコンテンツや諸資源にアクセスすることよりはるかに重要である”（Chan et al. 2019, 2）。

この流れに沿いふたつ目の例としてあげたいのは、鍵となるOSインフラの強化を視野に入れた長期的なつながりを支援する取り組みである。これは生物種・機関・国境を越えて収集された生物学的データを共有・解釈する方法を開発・維持するための、いわゆる「実践コミュニティ」を確立することである（Louafi et al. 2022）。植物科学の領域では、そのようなコミュニティのひとつとして、Consultative Group for International Agricultural Research Ontologies Community of Practice（国際農業研究協議グループ オントロジー実践コミュニティ）がある。このコミュニティは、作物データの普及に関連する学際的・国際的な専門知を結集するための、長年にわたる国家間の取り組みを公式化する形でまとめられたもので、2017年に設立された（Arnaud et al. 2020）。当該コミュニティは、作物データのインフラを構築するために、持続可能で責任ある、かつ効果的な手段の開発を支援したいと望む人々が参加できる。計算論的オントロジーに焦点が当られているのは、データを分類し、秩序立て、可視化するために用いられるキーワードや意味論的なツールに対する関心が共有されていることを反映している一方、複雑なデータを組織化およびマイニングするためにオントロジーを用いることに対してすでにある程度理解している人に参加者は限定されてもいる。当該コミュニティの参加者は、どのオントロジーを用いるかという決定が科学的にも社会的にも重要な結果をもたらすと同時に論争の的となることを認識している。中心的な関心事は、諸々のオントロジーの中で、どの程度まで植物の土着的ないしローカルな分類を取り上げるべきか、また、それらを科学的なタクソノミーとどのように関連づけるべきか、ということである。もうひとつの関心事は、グローバル市場やローカル市場にとって関心のある作物の形質を記述するために用いられる命名法についてで、特定のラベルを用いることによって特定の作物品種の商品化に対する関心を高められるか、あるいは低下させてしまうか、また、どのような種類の商品化が問題となっている作物の消費者にとってもっとも有益なのか、といったことを含む。このオントロジー実践コミュニティは、データサイエンティストから作物研究者、地元の育種家、農学者、政策立案者、農業ビジネス事業者に至るまで、さまざまなステークホルダーの専門知・視点をとらえ、伝達するデータ共有ツールの開発を目指した。こうした狙いを受けて、当該コミュニティの活動では諸集団間のつながりを確立することに重点が置かれてきた。相互理解を深め、交流の機会を提供することが目的として掲げられ、作物に関する信頼性の高い研究実践の諸システムを開発することに向けて信頼できるコミュニケーション経路の重要性もおさえられたうえで、である。ゆえにこの実践コミュニティでは、定期的にオンラインで意見交換する場を提供するとともに、さまざまな視点をもつ専門家の参加を積極的に促し、それら諸集団間で頻繁に議論をぶつけあうことが目指されている。

この領域に関与するのは、利害関係者たちが根本的に異なる、ときに相反する優先事項や目的に動機づけられているため、非常に困難なものとなる可能性がある（たとえば、データサイエンティストが技術的解決策に焦点を当てる一方で、育種家は所与の命名法を採用することでローカルな市場に及ぼす影響を懸念するなど（Williamson and Leonelli 2022））。それでも、このオントロジー実践コミュニティの活動は、議論の範囲を拡大し、それに応じてOSの実践を修正することに関心を寄せており、さらに同時に（ときには議論を呼ぶが）選択を動機づけしたり、多様な利害関係者への影響を検証したりしている点で注目に値する。このコミュニティの調整者たちは、自分たちのデータ共有ツールがどれだけ長く存続し、将来おこなわれる研究の参照点として受け入れられるかは、少なくとも部分的には、それぞれが互いにもつ視点を尊重しあうような形態を構築し、それによって新たに生じる懸念に対応し、参加者集団間で最低限の信頼を築いていくことにかかっていると認識している。このような取り組みは迅速に進むものではなく、短期的にはデータを共有することにとって効率的な方法ではないかもしれない。実際、このようなコミュニティは資金提供者や参加者の双方から常に脅威にさらされており、それらの活動は多くの場合、自動発見システムのために高度に標準化されて安定したオントロジーを提供する短期的な手段として描かれる。しかしCrowdfightの事例とは対照的に、実践コミュニティの認識論的価値は研究の選択と変化を長期的に支えるその力にある。このような形でつながりを醸成することは、OS実践の継続的かつ重要な要素として、より弾力的で包摂的なインフラやツールを生み出すことにつながり、それらがさまざまな視点やデータソースにさらされることで、農業政策について今後検討するうえで、いつどのようにして変化を促すべきかを判断するうえで、より有益な知見をえることができるようになるだろう。透明性はこのようにして、信頼と、諸々の発見・手順が信頼できるものとみなされうる状況についての共通理解が育まれる、包摂的で深慮深いプロセスを経て達成される。

このように共有された理解は、OSの試みに参加している全員のコンセンサスと同等ではなく、関係者間の合意を必ずしももたらすものではないことに留意されたい[^32]。むしろその焦点は、OSの取り組みにより結びつけられる、人間という行為者（および関連する実践の諸システムと絡む諸々の技術・資材・制度・非人間である行為者）間における親密性の新たな形態（ときに激しい意見の相違や不一致という形態をとることもある）を生み出すことに置かれている。この焦点は、OSツールが長期的にどのように構築・使用・管理されるかということに明らかに影響を及ぼす。たとえば、オンラインのデータベースを参照してOSに取り組んでいる研究者は、データベースを単に中立的なデータソースとして利用するのではなく、データベースがどのような仕方でつくられているか、検索可能なデータを作成した人々の労働条件について、時間をかけて習熟するよう促されるかもしれない。このような取り組みはデータの再利用を遅らせる可能性があるが、研究者からすると、どのような前提がデータの生成・提示のされ方を基礎づけているか、そのような前提がデータを用いる新しい文脈において意味合いをもつかどうかを知ることにつながりうる。これにより、新しい設定内でデータを処理および解釈できるかどうか、それはどのようにしてかということをより判断しやすくなり、より科学的に健全な研究をおこなえるようになる（Leonelli 2016, Borgman 2016, Mayernik 2017）。このような場合、当該サイト上で利用できるデータオブジェクトを単に収用するだけでなく、オンライン上のツールとのつながりを確立しようとすることで、研究者はその中にあるデータを文脈に位置づけ、既存の実践を見直しよりよく利用できるようになる。

[^32]: 私はコンセンサスの力に対するソロモンの懐疑論（Solomon 2001）を共有している。コンセンサスをえることができるまれなケースであっても、その結果、独自の境界戦略や排他的な前提をもつ新たなレパートリーが形成される可能性がある。

あるいは、研究者たちが自身らの手法を他者とどのように、どの程度の詳細さで共有するかを決めようとしている事例を考えてみよう。方法論を記述するうえで適切な形式、適切な公表プラットフォーム、適切な構成を選択することは、容易に標準化・自動化できるものではなく、というのもそれは、誰がそうした手法にどのような目的から関心をもつと予想されるかを考慮すること、それに応じて提示の仕方を組み立てること（その手法が悪用されにくいようにすることを含む）が絡むためだ。自身らの研究の手段や伝える相手のことに気を配るというのは経験豊富な科学者であれば誰もがわかっていることだが、この点は、データ駆動型AIを用いてそのような労力を省き、モジュラー方式で科学者らが研究オブジェクトにアクセスして利用できるようにしようと急ぐあまり、そうしたオブジェクトが背負っている問題や将来の研究への影響を吟味することなく、脇に置かれがちである。諸々の研究オブジェクトがもつ歴史性とそれらの文脈を切り離し、それらを解釈しようと向き合うのではなく、それらを共有するという課題に焦点を当てるのは、専門知がますます分散化された世界においては魅力的な提案であり、そこでは、諸々の研究コミュニティ間での個人的なつながりは、コミュニケーション技術やデジタルプラットフォームによっておおむね媒介されることになり、さらには置き換えられさえもする。しかし、そうした技術とプラットフォームに対する信頼・信用は、究極的には、絶えず変化する科学的および社会的な状況の中で、それらが目的に対して適切であるか、認識論的な多様性および正義をどの程度受け入れ支持しているかということを精査し続ける集合意思にかかっている（Lusk and Elliott 2022）。これは、デジタルインフラのブラックボックスを開けるためにそれなりの労力を費やし（Bowker et al. 2010, Nowotny 2021）、自身らの調査に関連した選択や前提についてだけでなく、そうした選択や前提が生み出された認識論的コミュニティについても特定しなければならないことを意味する。

ここで重要となるのが*思慮深い*つながりという考えである。研究におけるオープン性は単につながりを築く労力だけが必要なのではない。どのようなつながりが目下の科学的な取り組みにとって関連性があり有益であるかを評価しようとすること、そのためにそうした取り組みが及ぼす潜在的な（肯定的ないし否定的な）意味合いを検討しようとすることをも必要とする。つながりを構築することは不可避的に判断行為を伴い、その結果、新たな区分けや排除を生むことが絡む。したがってここで提唱しようとしているのは単なる社会化の運動ではなく、すなわち人々を互いに対話させるように仕向けていけば必ず肯定的な結果が生まれるという誤った期待を抱かせるものではない。また、ポール・ファイヤアーベントにより広く提唱されたように “すべての伝統は平等な権利をもち、権力の中枢に平等にアクセスできる”（Feyerabend 1978, 9）自由な社会を奨励するような認識論的同等性へと誘うものでもない。前述のように、科学の世界は認識論的不正義に満ちており、そうした不正義に対処することは、単にそのすべての形態における認識論的多様性を奨励し、その研究プロセスにおける潜在的参加者全員に平等な機会を与えるということを意味しない。むしろそれは、諸々の研究の取り組みに誰が参加でき参加すべきか、誰の観点が表明でき表明されるべきか、誰の考えが支持でき支持されるべきか、ということについてありうるビジョンの中から選択すること（「ロンジーノが「調整された平等性」と呼んだもの」）を必要とする。特定の研究の取り組みから誰が恩恵を受け、誰が損をする可能性があるのかをめぐって常に決定がくだされるわけだが、その選択はより明示的かつ内省的なものであればあるほどよりよい。認識論的多様性を考慮することは、*ただ単に*認識論的多様性を増やすこととは異なる。エージェンシー（行為主体性）とは一方を支持する立場を取ることが含まれ、それはファイヤアーベントが描いた自由な社会のモデルを裏切ることにもなる。オントロジー実践コミュニティでは、参加者らが作物の専門家とデータサイエンティストとの間の対立を絶えず裁いている。そうした裁定の結果は、どちらの集団も満足させないかもしれないし、一方を他方よりも大きく支持するかもしれず、それにより生じる影響は広がりとともに監視され評価される必要がある。Crowdfightの事例では、対立の解決策は現場の即時的なニーズに役立つものとなっている。参加者たちはほかの研究者の状況やニーズに注意を向けるように促されたのを受けてそれに耳を傾けてくれると期待され、また参加者たちは実際上の目的や目の前にある作業の条件とベストプラクティスの基準とを調和させる解決策を見出すことが期待されている。いずれの事例でも、つながりの構築と維持には思慮深さが求められる。それらには熟練を要する討議が欠かせず、問題とされたつながりがもたらす新たな機会は目下の文脈の中で評価されている。実際のところオープン性はそれ自体、研究プロセスとその諸々の成果物を価値づけるという動的かつ高度に状況依存的な様式として理解することができ、それは経済的・科学的・文化的・政治的・倫理的・社会的な考察を包含するものである（Levin and Leonelli 2017）。

オープン性をこのような行為遂行的なものとして理解するということは、関係者間でアクティブな共同関係を築く必要はないということだ。すでに述べたように、つながりは共同と同様に対立をももたらすのであり、新たな形態のつながりが合意ないし相互理解を生む保証はない[^33]。さらに、思慮深いつながりを追い求めるうえで、短期的にはCrowdfight、長期的にはオントロジー実践コミュニティに代表されるような、よく調整された社会的エージェンシー（行為主体性）を伴う必要はない。必要なのは、新しい研究のコンポーネントやインフラの開発やコミュニティの発展に伴い、その実体の生成に寄与した実践の（諸）システムや、それら諸システムで用いられた境界戦略が自身のものとどのくらい異なるかを探ろうと試みることに尽きる。いいかえれば、つながりをつくるというのは、関係する人々が自分たちの目的のために新たな要素を活用すべきかどうか、またどのように活用すべきかを有意義に判断できるような知識を獲得しようとすることである。先ほどの例に戻ると、研究者が自身のプロジェクトに関連するデータがあるかどうかを確認するために、新規のデータベースを参照することは、新たなつながりをつくることになる。そのつながりが自分の研究にとって役立つと証明するためには、そのデータがどのような条件のもとで生み出されたかを理解する必要がある。そのためには、誰がどのような目的で、そしてどのようにそのデータベースを作成したのかということに関するメタデータや情報を参照する必要がある——そしてその研究者は自身の専門知・経験・目的にもとづき理解し解釈することになる。このプロセスの一環として、当該研究者はそのデータベースや関連する実践の諸システムに対して、ある程度、親密さをえてなじむことができ、そのデータが自身の研究に適合するかどうか、どのように適合するか、また自身の境界戦略にとってどの程度のコストがかかることになるのかを判断するのに役立てる。このようなつながりが、やがて共通の目的をめぐる共同作業を促す場合もあるかもしれない。たとえば当該研究者は最初にそのデータが生み出されたラボのひとつを訪問しようと考えるかもしれないし、そのデータベースの開発に参加しようと考えるかもしれない。しかし、そのような明確な共同作業に至らない場合でも、思慮深いつながりは、他者性という新たな経験をもたらし、世界に対して自身がもつ観点や認識を修正する機会を与えてくれる。実りある意見の相違や摩擦が表面化して新たな反応や洞察が生まれるのは、諸々のつながりを確立することを通してであって、それは自身の境界戦略にとってそうしたつながりがどのような意味をもつかを評価することにより支えられている（Edwards et al.2011）。

[^33]: “繁栄する科学は、（悪魔が細部には宿るかもしれない）通常科学の集中的で、したがって認識論的には多様性に乏しいアプローチと、自由かつより多様で、批判的な内省の行使の両方を必要とする”（Radder 2019, 228）。

オープン性に関するこのような解釈は、現代の科学界や多くのOS政策に埋め込まれている価値の経済的定義を乗り越えるための批判的空間を生み出し、多様な関心やコミットメントが研究実践に影響を及ぼす諸々の仕方に細心の注意を払うものである。研究者らが何をどのように誰と共有するかを選択することは、関係する研究者らの目的・選好・制約・制度的状況に依存するため、公的領域と私的領域の間、あるいは研究が埋め込まれている社会性のさまざまなレイヤの間に明確な線引きをしてそれを維持するのは難しくなる。研究を構成するものや成果物を共有することについてなされるすべての選択の背後には、誰がどのようにそのオブジェクトにアクセスし再利用できるのかということに関する前提が含まれている。同じように、新しいオブジェクトを自身の研究に取り入れること、つまり新たなつながりを確立することについてなされるすべての選択の背後にも、そうしたオブジェクトが信頼でき有用なものであるための条件に関する前提が含まれている。ここで私が提唱しているのは、こうしたやり取りを、それぞれの実践の諸システムとそのようなつながりが自身の前提にもたらすかもしれない諸課題について関係する人々が批判的に精査することを伴う場合、アクティブな知識の探求にもっとも適したつながりの例として読み解くということである。

OSの認識論に対するこのアプローチは、すでにOS運動内の多くの取り組みで具現化されており、それには本章で言及した例も含まれるが、（テキスト・手法・ハードウェア・モデル・データ・研修・コードなどのいずれだろうが）研究コンポーネントを策定開発し、実際に誰がそれらを採用するのかということを明確に意識しないまま、自由にアクセスできるようにするというのではなく、特定のコミュニティや、状況に即したそれらコンポーネントの利用形態を理解し、支援することに焦点が当てられている。またそれは知識コモンズに関する既存の法学研究とも類似しており、そこでは共有されたオブジェクトとしてのコモンズという考えから脱却し、コミュニティ管理のあり方という社会的特性が代わりに強調され、それにより、社会的な関係性がもつ特定の諸条件や力学を考慮することが知識生産を目的として諸資源を利用する際に欠かせないことと認識されている（Frischmann et al. 2014）。このような研究が存在するということは、思慮深いつながりとしてのオープン性を主張する私の考えが新しいものでもなければ、OSの景観にまったく存在しないものでもないことを示している。本稿で私が試みているのは、そうしたアプローチとその哲学的基礎を取り上げ、特にオープン性という概念の枠組みを形づくる別の仕方と比較した場合の、研究およびそのガバナンスにとっての意義のいくらかを明確化することであった。結論として、思慮深いつながりとしてオープン性を理解することにより、共有する自由としてオープン性を理解することと結びつく諸課題のいくらかを克服する方法を明示し、それがOSの将来にとってどのような意味をもつかを概説する。

第一にそのスポットライトの向き先が、研究コンポーネント制限なきアクセスの追求から、諸々の研究グループと関連する実践の諸システム間の諸関係の性質、および、どれくらいのレベルの親密さや相互理解が所与のつながりの状況や目的にもっとも適すだろうかという点に移行する。諸資源にアクセスできたところで、適切なスキルをもちインフラ・ガバナンス・支援体制が整っていることで利用が促されるということ（それには最低限の理解と信頼が関係者の間にないといけない）がない限り、知識生産には結びつかない。具体的にそれは、そうしたつながりが自身の実践の諸システムと整合していているかどうか、それはどのようにしてか、それはどの点においてか、そして（それが欠けていることがわかった場合は）ある程度の互換性を確保するために何が必要かを評価する力のことである。OSの参加者が、関連する場や、相談してフィードバックを受ける仕組みをもっていることを保証するには、特定のツールを技術的に実現させるということを超えて、重要かつ長期的な投資が必要となってくる。これによりOSが、単に諸々のデジタル技術を自動制御により展開して迅速に結果をえられるようにするという、安価で手軽な研究活動の分業形態ではなく、むしろ資源集約型研究の変革なのであって、科学的な知識生産がより堅牢で包摂的なものになる可能性をもつことが明らかになる。ここでシティズンサイエンスについて考慮することは特に有用で、なぜならそれは、新しいつながりを築くことに重点が置かれ、その点がこの形のOSを特徴づけているにもかかわらず、一部のプロジェクトでは、科学者でない人々を単なる新しいデータの安価な供給源として利用し、データガバナンスや解釈のプロセスに参加者を関与させることに関心も示されなければ投資もなされていないためである（Strasser et al. 2018, Prainsack 2020）。これは私が「共有としてのオープン性」と関連して批判したオブジェクト指向で採取的な科学の認識論を反映しており、市民の経験が研究に有用な情報をもたらし、さらには研究を導く可能性があるかもしれないことを評価する際に役立てるどころか、科学的な専門知と一般的な専門知の間の既存の境界をむしろ強化しているといえる。

第二に、OSを本質的にデジタル技術に基礎づけられているものと解釈するのではなく、諸々のデジタルプラットフォームが既存および将来の研究をどのように支援できるかということについて、特に*特定の社会*環境内で複数のメディアを効果的に用いることについて批判的かつ建設的に精査することに関連したものとしてOSはとらえられることになる。デジタルメディアは、どんなに洗練されていてもアクティブな知識を伝えるには十分ではなく、生物学的データを共有する事例のように、研究者同士が互いのラボを訪問し、機器や標本、実験スペースの新しい扱い方を学びあう交換プログラムのような、アナログの取り組みにより補完される必要がある。社会的側面への配慮は、研究システムにおける人間の役割にも及ぶ。科学者個人の選好や行動にのみ焦点を当てるのではなく、注目すべきはむしろ、そのような個人と、彼らの研究生活を組織するさまざまな集合体（地域の集団から国家機関や国際社会に至るまで）との間の相互作用であり、そして、それら社会的に形象されたさまざまなものが並置されることによって、（それらが交差したり重なり合ったりする／しないかに関わらず）個々のエージェンシー（行為主体性）や判断にどのくらいの影響が及ぼされるかという点である。さらに、特にシティズンサイエンスやオープンソースコーディングの場合、専門的な研究ネットワークは、活動家やロビー集団を含む、科学以外のネットワークと交差する傾向がある。つながりを促すことを目的としたOSにおいては、そのような結びつきが、研究の取り組みに貢献しうる可能性があること、あるいは（ワクチン接種や気候変動の否定をめぐる政治的な論争で明らかなように）有害な効果をもつことを明示的に整理・認識しておく必要があるだろう。

この点が、「思慮深いつながりとしてのオープン性」という見方におけるOSの第3の特徴を導く。この見方では、OSの介入がその影響において世界的に有益であるとはみなされない。ほかの社会変革と同様に、OSは必然的に*分断を伴う*ものと理解される。「最善の研究実践」を構成するものをめぐってコンセンサスを探し求めたところで、往々にして何らかの抵抗に直面するのは驚くべきことではない。どのような実践の変化も、ある研究環境の参加者の一部にとってはよい影響をもたらし、ほかの人々によっては負の影響をもたらすことになる。諸々のOSの取り組みがもつこの排他的な力を認識すること——たとえば、新しいつながりを構築することは、人間の注意力には限界があり、どのような実践の諸システムでも境界戦略に基礎づけられているからという理由だけであっても、既存のつながりを手放すことを伴う場合が多いことを気に留めることによって——は、研究における既存の不公正および差別に対処するうえで欠かせないことである。それは、オープンな研究やインフラを発展・開発する際に、関連する諸技術がどれほど包摂的なものであると約束されていたとしても、価値判断は避けられないことを受け入れるということである。そして、理想的には関連する専門知をもつ人々との共同作業のもと、どれほど善意なものであったとしても、どのような取り組みにもある利点・欠点を明示的に研究することを意味する[^34]。いいかえれば、OSとはつながりをつくることだけに関するものというだけではなく、次に向かうべき方向性という物議を醸す価値負荷的な決定をおこなうこと、失敗や予期せぬ負の影響に照らしてそうした決定を修正できるよう準備しておくことに関するものである。

[^34]: これは「責任ある研究・イノベーション」、そしてデジタルトランスフォーメーションに関する科学研究の中心的なメッセージであり、新たな洞察ではまったくない。

この点を踏まえると、思慮深いつながりの重要性に敏感なOSの取り組みは、目下の探究状況に適切なように認識論的正義を醸成させることに役立つ諸々の仕方で、認識論的に多様な実践の諸システムの複数性にあわせて調整されることになる。共通の標準と技術的なプラットフォームの策定開発は、ローカライズ（特定の地域に適用できるように修正）されたエージェンシーを支援する限りにおいて有用である。OSは、たとえばローカルな環境に対応する修正をおこなうことが明確に示されて考案されたツール（CrowdfightやGitHubなど）や、OSの参加者がフィードバックをおこなうとともにOSのガバナンスと将来的な開発に参加できるような仕組み（実践のコミュニティなど）があげられるが、*状況に応じた解決策*を目指す必要がある。こうした解決策には、特定の形態のOSから、誰がどのように、そしてより広範な研究環境にどのような影響を与えながら、恩恵を受けるべきなのか、受けることができるのかということをめぐる優先度の順位づけが不可避的に含まれる。何らかのOSの取り組みによりどのユーザが特権を与えられることになるかが明確に特定され、そうした選択の明確な根拠が示されるのであれば、あたかも「誰にとってもよい」ものであるかのように装うよりは、OSの表され方としてはより誠実で実りがある。また、それらの取り組みの信頼性を高めるだけでなく、そうした取り組みの認識論的位置づけおよび価値、そして関連する変革の提案に対する継続的な評価を促す。

これはつまり、OSの取り組みから誰が恩恵を受けるべきかを選択するということは、規範的かつ往々にして道徳的な立ち位置を取ることを意味し、研究実践における認識論的な諸問題と規範的な諸問題が深く相互に関係していることを認識したうえでおこなうということを意味している。諸資源を自由に広く共有することが主張されるときにしばしば見られるように、平等への幅広い訴えは、原則としてすべての人が諸資源にアクセスできる場合であってさえも、すべての人が自分らの目的に対してそれらを有意義に利用する機会を平等にえられるとは限らないため、役に立たない可能性がある。したがって私は、OSにおける公正という分配的な考えから離れ、代わりに既存の不公平を緩和し、潜在的な参加者のうちもっとも弱い立場にある人々の中で有意義に活用できる能力を積極的に育む方向に軸を置く公平なアプローチを促すことを支持する。オープンサイエンスの諸々の取り組みは、対象とする研究環境の特性がOSの取り込みを促進ないし妨害するかどうかを評価し、その提案を現在の状況に適応させる責任がある。低帯域幅の状況および／ないし脆弱な機関で働く研究者を特に対象としたOSの取り組みが最近増加していることは、この点で心強いことであり、また、実行に必要なエネルギーやハードウェアをめぐる環境的・社会的な懸念事項に配慮したインターネットプラットフォームが確立されていることも同様である[^35]。

[^35]: Research Data Alliance（研究データ同盟）の専門作業部会およびKM4Dev Wikiの項目「低帯域設計」<http://wiki.km4dev.org/Low-Bandwidth_Design> (last modified 18 Feb 2012)を参照のこと。

これらの主たる特性の分析から、オープン性を思慮深いつながりとして位置づけることは、科学的・社会的に有益な形態のOSを達成し、特にオープン性を共有する自由として位置づけることと比較した場合、研究における「ベストプラクティス」に対する既存の理解を改善するのに役立ち、かつおそらく必要でさえある、と結論づけられる。つながりと判断の重要性に焦点を当てることで、人間による意思決定と社会的な文脈が科学的な知識生産、特に諸々の研究成果について伝達・共同・具体化する戦略の中核に据えられることになる。このように人間という参加者を中心に据えたOSを再構築しなければ、OSは、研究成果およびその使用をコモディティとして扱う技術管理的な統制下におかれた別形態のものになってしまうリスクがある。思慮深いつながりという考えを軸としたOSの枠組みは、OSの哲学の規範的な基盤として機能し、その完成形や意義については本稿の範囲内で包括的に議論することはできないものの、その将来的な発展形は、閉ざされた科学に関連する研究上の諸問題に対処するのに必ずや役立つと考えられる。

| 共有としてのオープン性                      | 思慮深いつながりとしてのオープン性                                 |
|---------------------------------------------|---------------------------------------------------------|
| 制限なき                                      | 関係性                                                  |
| デジタル                                     | 社会的                                                  |
| 善                                           | 分断的                                                  |
| グローバル                                   | 状況依存的                                              |
| 平等                                         | 公平性                                                  |
| 焦点はアイテム化された諸々の成果物（共有可能なオブジェクト） | 焦点は社会的エージェンシー（他者と行為するおよび他者と存在する諸々の仕方） |

: 表3. 本稿で論じたオープン性に関するふたつの解釈の比較
