# 実践について再考する：オープンサイエンスの実装に関する諸課題

第2章では、共有としての「オープン性」という見方にもとづくOSが、研究者・研究機関・資金提供者のいずれにとっても魅力的な展望と映っている理由を明らかとした。本章では、OSが日常の科学実践で具体化されればそうした展望が実現されたことになるのか、それはどのようにしてかといったことを検討する。ここではOSの実装について4つの試みを簡単に検証するが、研究エコシステムのオープン化に内在する機会および課題をそれぞれ示している。選んだ中で顕著な例はオープンデータだが、それは実践している研究者のもつオープン性に関する主な仮定や期待をデータ共有の議論が例証するものだからであり、また、知識生成のためにデータをどのように利用できるかというさまざまなビジョンに根拠をもたらす概念的なコミットメントと倫理的なそれとの間の深いつながりを示すものだからだ。実際にデータ管理は、オープンソース、オープンアクセス、オープン査読、オープンメソッド、オープンインスツルメント、シティズンサイエンスに依存し、大きな影響を与えている。ゆえにこれらの例が示す緊張関係は、データの利用とガバナンスということだけにとどまらず、OS戦略を策定・適用していくうえで根底となる、技術的・社会的・倫理的・概念的に入り組んだ諸課題について知る機会となるだろう。

## アクセス戦争：COVID-19のデータ共有

最初の事例はCOVID-19パンデミック関連研究の国際的な共有についてである。これは、研究を加速させ、ソーシャルディスタンス・検疫隔離・ワクチン開発といった緊急対策時の意思決定を支えたという点から、OSの価値と力を示したものとして広く賞賛されてきた。コロナウイルスSARS-CoV-2に関するゲノムデータの配布は特に成功し、世界中の何百もの研究施設間でウイルス株に関するデータを迅速に共有する機会をえたことで、新たに注意すべき変異株の特定、COVIDワクチンの基盤となるメカニズム、重症感染症の治療法の可能性など、多くの発見がもたらされた。だがこの領域におけるデータ共有の取り組みの中には、“十分にオープンではない” ことや “効果的なデータ共有を阻む障壁” を生じさせていることから、攻撃の矢面に立たされているものもある[^12]。攻撃の理由のひとつは、ヒト以外の遺伝データを制約なしに共有するという分子生物学における既存の約束事と異なり（Maxson Jones et al. 2018）、こうした取り組みの一部ではデータのアクセスと再利用のされ方に制限が課せられていることがあったためである。

[^12]: このOpen Letter (2021) はそののち Nature で報告された。

GISAID（Global Initiative on Sharing All Influenza Data）の事例を簡単に考えてみたい。このデータベースは、もともとはインフルエンザに関するデータを共有するために2008年につくられたものだったが、2020年1月にSARS-CoV-2データへアクセスできるようにすぐさま再デプロイされた。このデータベースを利用するには合意書に署名が必要で、もとのデータ作成者のクレジット（貢献）を適切に示すことを保証せねばならず、GISAID上で保管されたデータをほかの情報源とリンクさせたり統合したりする方法にも制約が課せられる。この要件は、（往々にして、諸々の資源に乏しい環境で、および／ないし、あまり注目されていないところで研究している）一部の研究者が、設備が整ったところの研究者が十分な謝辞なしにそのような成果にもとづく研究を進めてしまうことを恐れてデータ共有したがらなくなるという認識から来ている。そうした不安は正当なものだ。オンラインで利用可能なデータを再利用するには、信頼できる強力なネットワーク環境や計算資源が必要だし、裕福な機関に拠点を置く研究室の理論的観点および物的能力に合致する基準が採用されていなければならない。それゆえ低資源環境にある研究者は、その研究がいかに革新的で厳密であっても、常にオープンデータを活用できるとはいえず、オンラインコレクションへ自身が所有するデータを提供することには消極的なままである（Bezuidenhout et al. 2017）。GISAIDのユーザポリシーは粗雑ではあるものの、こうした問題を相殺するには比較的効果的な試みである。公式な合意書とクレジット表記の仕組みが整っていることで、地政学的な状況、資金レベル、物質的資源、社会的特性が大きく異なるグループ間での情報交換が促され、2023年2月までに240か国の研究者が合計1500万の塩基配列を共有することとなった（https://gisaid.org）。同時に、データへのアクセスやリンクが可能な範囲を考慮しなければならないことから、GISAIDデータはほかの情報源との統合が制限されており、研究の速度と幅には悪影響が及んでいる。そのため、パンデミックに対する有効な対策の緊急性を懸念する何百人もの主導的な研究者たちからの反発を招いている。

Global Initiative on Sharing All Influenza Data（GISAID：インフルエンザの全データ共有に関する国際事業）は、研究グループ間での力・諸資源・知名度に根深い違いがあることを認識したうえで構築されていた。データ作成者の権利保護に重点を置いたデータガバナンス構造は、資源を豊富にもつ機関の研究者と資源に乏しい機関の研究者の間の不平等に対抗する試みである。これらの問題を迂回することを選択して「完全にオープンな」データを求める研究者たちは包摂という問題よりも透明性という考えを優先している。この姿勢は理解できる。COVIDデータを一括ダウンロードして自由に探索ないしリンクさせられれば、それら諸資源を斬新な形で観察したりさまざまな形で解釈したりすることが容易になる。こうした利点は、研究者たちがすぐさま分析・解釈できるくらいに十分な規模で整備されたデータ資源を求めて躍起になっているときには特に過小評価できない。だが制限なき共有の技術的・科学的利点に焦点を当てることで、社会文化的な要因（地政学的な状況や研究者の特性など）、制度的な問題（研究拠点間の力関係や知的財産をめぐる期待など）、データ再利用を支えるインフラ資源（資金の入手可能性や信頼できるネットワーク環境など）などに注意が向けられなくなってしまう。こうした要因を無視することは認識論的リスクを伴う。高度なインフラに支えられた高速な研究に重きを置くことになってしまう——しかしこうした要因が、必ずしも質や長期的な信頼性の指標とならないし、なるとも限らない（Chan et al. 2019, Leonelli 2021）。その結果、権威ある学術機関に所属していない研究者はデータ共有の取り組みから排除され、それによりオンライン上で利用可能なデータの多様性と範囲は減少するだけでなく、根拠の基礎となるものの評価時に重要とみなされる専門知の種類も減少する可能性がある（Sheehan et al. 2023）。ここには、誰が研究に参加し、参加者として認識されているかという点で重大な倫理的問題がある。しかしこのようなバイアスは、単に倫理的な問題であるだけでなく、認識論的な意味合いも含んでおり、というのもそれは、生物医学研究者が国際的に利用可能なデータ資源の多様性と、データのモデル化および解釈に活用される専門知（特に局在的・地域的な専門知）の量の双方を大幅に減少させてしまうためだ。大規模なデータマイニングや分析に役立たないとしてGISAIDの手順を批判するには十分な理由がある一方で、GISAIDではデータの生成・クレジット表記・商品化という文脈に配慮されているわけで、それは、研究における不公平さがもつ科学的な意味合いを強調し、未来の研究にとって根拠となる基盤（エビデンスベース）をよりよいものにしていく解決策をつくりだす貴重な試みとなっている。

GISAIDとそのガバナンスをめぐる議論は、特にオープン性が何よりもまず共有の一形態として解釈され前面に打ち出される場合に、オープン性の原則に従う試みと、その研究が認められていない、および／ないし、差別されている研究者の保護を意図した責任ある研究の方策とがいかに衝突しうるかを例証している。科学は公平な競争の場ではない。データ普及のために、信頼に足る明示的に非搾取的な条件を提示することは、研究への参加者を広げるのに役立ち、ひいてはそののちの発見の根拠となる基盤を拡大させる（Chan et al. 2019）。それはまた、質の低いデータの流通（Leonelli 2018a）、デジタル格差の拡大（Bezuidenhout et al. 2017）、社会的に有害な研究の追求（Elliott and Resnik 2019）を防ぐこともできる。したがって、悪しきOSの例としてGISAIDを攻撃するのではなく、完全に透明なデータ流通は難しく、クレジットが明示されないこともあることは一方で認識しつつ、GISAIDデータの使いやすさの向上に協力する方が有益なように思えるのである。

## 実践のマングル [^101]：技術と質の基準

[^101]: （訳注）古賀 (2017) によると、“実践のマングルとは，科学研究の旗手の一人である Pickering が提唱する概念...... ここでいう「マングル」とは、昔の洗濯機についていた「乾燥兼皺伸ばし用圧搾ローラー」のことで...... 彼は、マングルが作動するとき、人間や物が相互に関わり合い、それらが一つの塊として織り込まれると考える”。なお、[エクセター大学のウェブサイト](https://spspa.exeter.ac.uk/sociologyphilosophyandanthropology/people/profile/index.php?web_id=pickering)によると、Andrew Pickering は原著者の所属先と同じエクセター大学名誉教授でもある。古賀広志 (2017) 「実践のマングルとしての情報システム」『日本経営システム学会誌』34(2), 205–213.

中国とインドが科学大国として台頭し、アフリカや東南アジア、南米で科学従事者が急増しているにもかかわらず、彼らはみな、合理性とベストプラクティスに関する世界基準を定める際に西洋科学の優位性に挑戦してきた（Harding 2011）。英米の学術界をモデルにした特権的な機関が設定した査定・クレジット（貢献の評価）・品質管理の体制は研究のランクづけや評価体制を支配し続けている。研究者自身とそれらの研究を評価する人々によって、すぐれた研究実践は少なくとも部分的には特定の技術へアクセスできることに依存する、という認識が広まっていることはその帰結のひとつである。この認識はOSの取り組みにとって重要な意味合いをもつ。

OSがフリーオープンソースソフトウェア（FOSS）に与えている重要性を考えてみたい。FOSSは制約なしに、あるいは高額な料金を払わずにアクセスおよび変更できるため、導入に障壁はない。プロプライエタリなソフトウェアは対照的に、その利用料は高額で、コントロール対象下にある。科学研究にFOSSを採用することは、資金援助がほとんどえられない人々にとっては明らかに有益なことと思えるかもしれないが、資源が乏しい環境にいる研究者が自身らの研究を支えるためにどのようにソフトウェアを選択・使用しているかを見るとそうはいえない。たとえばグローバルヤングアカデミーがバングラデッシュ、ガーナ、タンザニアの研究者を対象に実施した調査では、高価なプロプライエタリソフトウェアを彼らが好んで使用していることが浮き彫りになった（Vermeir et al. 2018）。これは同等のFOSS代替品が使用可能で、プロプライエタリなツールに支払う資金をえることが不可能ではないにせよ困難である場合にも確認された。このような選好の理由のひとつは、オープンなソフトウェアを使用することにスティグマ（劣等意識）を感じていたというものである。調査の参加者の中には、特に国際的に知名度が低い研究機関から投稿されたものの場合、国際学術誌の編集者や査読者はFOSSの使用を低品質な研究の印と解釈するだろうと考えるものもいた。対照的に、 *MatLab* や *Mathematica* のようなよく知られたプロプライエタリソフトウェアを使用することは適切な方法論に関する世界的な考えに沿うものとみなされ、英米の学術ジャーナルで研究結果を公表することが促されている。データセットの品質評価に関しても同じような議論がなされており、これはデータを作成するために用いられる技術に依存すると理解されていることが多い。たとえば、高性能配列解読装置の最新モデルは、目下の研究目的に必要なデータ精度のレベルにかかわらず、以前の、そして現在では安価なモデルの使用よりもすぐれたものとみなされている（Leonelli 2018a）。

ベストプラクティスとみなされるものについてのこうした認識は正しくないかもしれない。実際の評価プロセスよりも研究者の偏見を反映している可能性がある。いずれにせよ、OSの実装にはこうした認識が極めて重要であり、OSツールは特定のタイプの研究環境や文化の中でのみ有効であり、ほかのものは排除されている。特定の技術が好まれるかどうかは、そのツールが目下の科学的課題に適しているかどうかとは別の要因によって決まることが判明している。こうした要因には、特定の技術を採用するための適切なトレーニングや支援を受けられるか（ないし受けられないか）といったインフラ的なものや、科学出版の構造、査読者や編集者が果たす強力な役割を含む組織的なものがある。あるいは、各分野を特徴づける評判のヒエラルキーや、資金力のある研究室がほかの研究拠点の模範となるべきという一般的な思い込みのような社会文化的な要因もあげられる。これらの要因は実施される研究の種類に影響を及ぼし、研究者はその使用に伴うスティグマを理由として潜在的に有用なツールの探索をためらう。共同研究の戦略にも影響が及ぶ。国際的な公表には欠かせないとされる諸々の資源やインフラにアクセスできない研究者は、そのようなアクセスを提供してくれる裕福な研究機関と提携することを選択するか、あるいは結果をローカルな場でのみ公表するか、まったく公表しないことにすることが多いためだ。したがってある研究の可視性・評判は、さらには自己評価さえも、高度な技術へアクセスできるか否かに依存しており、技術的な選好とは、研究評価、資源調達、地政学的位置づけという特定のシステムを具体化したものである。FOSSや安価な配列解読技術は理論上価値があると認識されているが、実際の使用は、信頼できる科学とみなされているもの、そしてそれを決定する主体に関する既存の（時に矛盾する）前提と衝突する。このことはFOSSや関連する取り組みの価値を低下させるものではなく、むしろFOSSの採用を支えるのに必要な研究環境を体系的に変えていくうえでは文脈の考慮が重要となることを示している。

## データ取引：作物データの連携およびバイオプロスペクティング

OSの実装にとってもうひとつ重要な要因は、研究要素が開示され取引される際の政治・経済的な状況である。作物に関する研究データの普及と、持続可能な栽培というものの構成要素や高収量作物品種の重要性に関する概念的仮定の広まりとの関係を考えてみたい。世界中の研究者・育種家・農家によって大量に生み出される作物データは、プラネタリーヘルスに関する研究にとって極めて重要である。植物ゲノム、生理学、成長パターン、環境応答に関するデータを統合することで、高収量単一栽培から脱却した農業の再構築や、作物の生物多様性や気候変動への耐性に関する知見を活用し、世界中の持続可能な栽培や保全活動を後押しするなど、食糧安全保障を確保するための新たな戦略を導き出すことができる。そのため、植物データが最初に収集された場所とは関係なく、それらをリンクさせ集合的な形でマイニングしうる方法に大幅な投資がなされてきた。データが抽出される情報源や資材には膨大な異質性があり、そのような多様性を適切に記録できるフォーマットやインフラを開発することの困難さを考えると、この領域におけるデータ連結には依然として計り知れない課題が伴う（Williamson et al. 2023）。しかし、データ共有をめぐる技術的な課題に特に焦点をあわせた場合、地域の育種家・政府・農業関連業界の間でのデータ取引に関する政治的な駆け引きや、遺伝子選択により植物の収穫量を増加させるといった、技術主導の解決策を重視した農業開発について理解をえられるように、植物科学でえられた根拠を用いたりすること（たとえば精密農業についてはMiles 2019）など、そうしたより広い文脈に研究者は対処できていないことが多い。知的財産（およびその結果もたらされるイノベーション）の制度が将来どのように適用されるのかということをほとんど考慮せずに、国際規模のデータベースでデータを広く利用できるようにしてしまうと、自分たちの労働力と専門知を通じてデータを生成する当の農家や育種家にとってはリスクがもたらされることになる。データ収集に貢献する先住民や農業コミュニティが、金銭面や評判の面だけでなく、将来的にそれらデータがどのように利用されるかの決定に関与できるという点で、（もしあるとすれば）どのような恩恵を受ける可能性があるのかは不明なことが多い。

これらの問題は、作物データインフラの開発と利用を支える植物生物学をめぐる理論的前提に影響を及ぼす。たとえばオープンデータベースによって促進される作物科学では多くの場合、病原体や環境ストレス因子に対する抵抗性を示す作物品種を特定するために植物ゲノムに関するデータ（いわゆるデジタルシーケンス情報）の共有・解析が重視され、そうした品種を商業的に開発・取引することが保証されている。この活動は認識論的にも倫理的にも中立ではない。文脈から切り離した形で遺伝子配列や関連する植物体（遺伝資源）の流通を促進させることで、このアプローチは、環境的・社会経済的背景を含む、そうした対象物が産まれた来歴に関する情報を整然と軽視する。ゲノムデータは現地にある植物の表現型を対象とした観察や現地での用途よりも優先され、もっとも広範なデータコレクションでさえ、文化的・環境的・生物学的な違いは往々にして犠牲にされ、地点間の円滑な比較を促すために標準化される。このことは、育種家や地元農家の植物知識が完全に無視されることを意味するものではない。むしろそうした知識は植物研究者が（特に分子的なアプローチで）おこなう優先順位づけや分類というレンズを介して流用・整理・表現されるのである。この領域では、植物はどのように研究・理解されうるかということが再考されていることを含め（Leonelli 2022b）、データの作成者と利用者の間での協力関係をより公平なものにしていこうとする仲介的な努力が果敢になされているにもかかわらず（たとえば国際農業研究協議グループ実践コミュニティがあげられるが、彼らのOSに対する理解については第5章で述べる）、総じて以前から、作物データへのアクセスとその再利用のガバナンス体制は高収量作物の特定・栽培を前提とした農業開発について特定の理解をもち活動する限られたデータ専門家グループの管理下にある。その結果、作物の生物学・生態学に対する科学的理解は歪められている。このような文脈から切り離されたデータからえられた知見がコモディティ化され、それについて異議は唱えられない状況が続いている。現地でえられた情報を高価な製品（種子・肥料・農薬）へと変換し、それを農家に高値で売りつけるという、農学分野で確立された傾向は変わっていない（Bonneuil 2019, Curry 2022）。こうした状況においてオープンデータの利用はバイオプロスペクティングの別形態となっており、つまり、農業分野の大企業の利益のために恵まれない地域から諸資源を採取する行為となる。

このように一方では、植物データを幅広く連結させていく探求は、人間に消費される植物の生態学的特徴や、それに関連して、自給的農業、伝統作物の地産地消、農文化の多様性といったことの諸々の利点を含め、農業のさまざまなモデルを探りたいという願いによって動機づけられている。もう一方でこのような探求は、概念的にも実践的に限界を伴う。そのデータシステムでは、ほかのエビデンスよりも遺伝子データが系統的に重視され、食料安全保障の点からは市場主導モデルが支持され、世界の北と南でおこなわれている作物研究を特徴づける不公平さに対処できていないし、あるいは大半の作物科学を支える搾取的な植民地支配の長い歴史にも立ち向かえていない（Leonelli 2022a）。研究データ同盟のようなデータ機関や国際連合食糧農業機関のような国際機関では以前からこの問題は認識されており、オープンデータの要請とバイオプロスペクティングの実践を切り離そうとしてきた。そのためには先住民グループ・農家・育種家がもつ権利と見方を受け入れながら農業の改良を目的としたデータ取引を促すような（技術的ツールと政治的ガバナンスの両方を含む）洗練された形態のデータ管理が必要となる（Williamson and Leonelli 2022）。問題となるのは、何を重要なデータとみなすのか、いつどこでどのような目的でそれらは用いられるのか、またどのようなモデル・手法・アルゴリズム・公表形式がそうしたデータを分析するのにもっともふさわしいのか、といったことの決定である。このような決定は、関連する専門知をもつ多くのコミュニティ間の対話によってなされるのではなく、むしろ、技術的・商業的な関心（植物に関する正当な知識として受け入れられることの範囲が定められることになる）に従いなされる傾向がある。そのため、データ共有の改善を狙いとした連結戦略は知らず知らずのうちに植物が研究され管理される認識論的空間を平坦化し、既存の農業開発体制によって、データに記録しようとしている生物学的・文化的・環境的な多様性そのものが消し去られてしまう可能性がある。

## 方法論の衝突：再現性の「危機」

最後の例は再現性の原則をめぐる激論に関するものである。再現性とは広義には首尾一貫した結果をもたらす仕方で既存の研究を再現できることとして理解され、しばしばOSのひとつの柱として、少なくともふたつの仕方で提示されることが多い。第一に、OSはデータ・方法・コードの共有を要求しているように見える点で、それらなしにはそもそも再現に取り組むことが間違いなくできない。第二に、OSは信頼できる研究結果と疑わしいそれを識別するのに役立つと期待されている点で、それによって公表された結果の質が証明される（Burgelman et al. 2019; National Academies 2018, 2019; Leonelli and Lewandowsky 2023)。しかしこの10年にわたり、心理学や生物医学において重要な研究の再現に失敗する事例が立て続けに生じたことが広く知られ、より一般的にも、公表された結果の信頼性に深刻な疑問が投げかけられている。このような懸念は、諸々のジャーナルで実施されている品質管理に不備が見られること、（pハッキングや選択的報告などの）不正な、あるいは疑わしい研究手法の排除が困難であること、オンラインで公表された結果の信頼性をチェックする責任が誰にあるのかが明確でないことなどが原因で、さらに悪化している。こうした不信がうごめく風潮のなか、科学と疑似科学を区別する規準として再現性がしばしば引き合いに出され、[その規準に] 準拠していない研究は信頼できない可能性があるものとみなされる（Open Science Collaboration 2015）。無作為化臨床試験やモデル生物における遺伝子ノックアウト実験など、目的が事前に設定されたうえで高度に統制・標準化された実験は再現可能な研究の実例として認められており、より一般的にもすぐれた研究実践のモデルとして提示される。そのような統制された環境で作成されたデータやプロトコルは、多くの場合、デジタル形式で入手され、首尾一貫したメタデータが付されていることから、共有や再利用がもっとも容易なもののひとつでもある（Leonelli 2018b）。しかし、管理体制がそれほど厳密でない研究のあり方は消えてしまうことになるのだろうか、そして、過度な標準化——研究者と研究対象との相互作用を、つまり斬新で意外な知見をえるチャンスを想定しすぎることによって——が調査を台無しにしてしまうことはありうるだろうか。

哲学者たちは、どのような一群の手法・スキル・設定・データの種類・対象・概念的仮定・目的がある特定のプロジェクトに関連するかが明らかになるのに応じて、再現性はさまざまな形態を取りさまざまな意味をもつと指摘してきた（Radder 1996, Romero 2019, Guttinger 2020）。同じ学問分野であっても、コンピュータシミュレーションを複製することに帰せられる重要性には劇的な違いがありうる。研究環境の設定が高度に統制されている場合、その人工的な性質から、手順も結果も完全に再現可能であることが期待される。フィールドベースの観察の場合、研究環境の設定はほぼ統制されず、再現されるのは結果そのものではなく観察者のスキルであることが多い。または（環境・社会・気候的に）変化する条件下で実施される実験の場合、差異の検出は用いられている手法に対する否定とはならず、新たな調査の開始点となる（Leonelli 2018b, Feest 2019）。高度に統制された実験を再現可能な研究のベストプラクティスとなる普遍モデルとして採用してしまうと、それにもとづいてほかの形式の研究は評価され、諸々の結果は多かれ少なかれ信頼できるものとみなされることになってしまい、ゆえに有害となりうる。同様に問題なのは、研究の質を示す指標として再現性をもちあげる人々がしばしばおこなうが、研究プロジェクトは最初から精密に定義された目標をもつべきだとする前提である。これは、明確に定義された仮説を検証することを目的とした臨床試験に例示されるような状況では意味があるが、関心の対象となる現象を特定したり特徴づけたりすることを狙いとした探索的調査には当てはまらない。

再現性に対するこのような狭すぎる解釈は、研究者が研究中にくだす台本のない判断にまで——そうした判断が苦労してえた専門知や手元にある対象への理解に基礎づけられていようがいまいが関係なく————現在の不信感の風潮を広げてしまう危険性がある。これは研究の生産・処理・評価における熟練の専門知や体現された知識の役割、社会的文脈の重要性を軽んじている。したがって本章で述べたOS実装の例でも確認したように、再現可能性を普遍的なものとする見方を支持する試みは、領域の専門知（の諸々の境界）に対する理解にとって悪影響をもたらしかねない。科学全体の境界を設定する戦略として再現性を一枚岩のように理解することは、特定の目的・概念・対象にあわせてつくられてきた多数の貴重な手法があることから目を背けている。同じ研究を繰り返し、そこに違いを発見した研究者にとって、「なぜこの結果は違うのか」と問うことは、「どこに間違いがあるのか」と問うことよりも価値がある場合がある。実際のところ再現性を訴えるだけでは、研究条件の違いから、意図的でないミスや意図的な不正行為、あるいは一般に受け入れられている事実に対する巧妙な反論まで、論争中の結果に対してさまざまにありうる説明を研究者は区別することができない。また再現性をアピールすることが結果の信頼性や質をめぐって長い間もたれてきた疑問に対処するのに常に役立つとも限らない。というのも再現性をアピールしたところで、科学の出版文化や責任あるデータ管理に対する信用の欠如といった体系的な問題（研究者に対して、研究の結果を過度に一般化し、十分な検証をしないように促しているともいえる）に対処することには役立たないためだ。再現性という狭い考え方は、研究の質を評価するという厄介な問題に対する単純かつ一般的な解決策としては魅力的に映るかもしれないが、方法論的・科学的な多様性について認識し大切にしなければ、科学の進展に深刻なダメージを与える可能性がある。一方で再現性は、結果の検証に対する見返りが乏しいことや、作物科学などの領域におけるOSの取り組みに浸透している不公平な状況など、システム上の文化的・制度的な諸課題に対処するのに役立たないことも明らかである。
